### ISSUE TITLE
Dosage - Do not allow unstructured dosage text when normal/split dosing (Oliver Egger, ahdis ag )

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#103]
ch.fhir.ig.ch-emed#2.0.0 /dosage.html

Dosage - Do not allow unstructured dosage text when normal/split dosing

see https://github.com/ahdis/ch-emed-pmp/issues/8

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
Open issue: https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.60&language=en-US
