### ISSUE TITLE
Split dosage: Dosage.sequence

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#105]
@pjolo & @oliveregger 
Would we have to change the sequence numbers for the dosage format 1-1-1-1 so that the sequences each have the same numbers?

[Dosage.sequence](http://hl7.org/fhir/R4/dosage-definitions.html#Dosage.sequence) - Requirements	
_If the sequence number of multiple Dosages is the same, then it is implied that the instructions are to be treated as concurrent. If the sequence number is different, then the Dosages are intended to be sequential._

* CH EMED - current example with different sequence numbers: e.g. [2-3-MTP](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/Bundle-2-3-MedicationTreatmentPlan.json.html)
* Multi-sequence Instructions
   * https://nhsconnect.github.io/Dose-Syntax-Implementation/dosage-sequence.html
   * https://simplifier.net/guide/dosesyntaximplementationguidanceforfhirstu3/sequence?version=current

******
@oliveregger 
* Would this have an influence on the mapping?
* Would it make sense to add a constraint in the profile?

**Comment by pjolo** [comment]
@ziegm and @oliveregger 
After the instruction of Multi-Sequence, the sequence number should in fact be adjusted so that the sequences each have the same numbers.

**Comment by ziegm** [comment]
Check the congruence to CDA -> [Dosage Instructions PCC 6.3.4.16.20](https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_TF_Rev10.0_Vol2_FT_2014-11-04.pdf) (page 171/224) 
_The value of the <sequenceNumber> shall be an ordinal number, starting at 1 for the first component, and increasing by 1 for each subsequent component. Components shall be sent in <sequenceNumber> order._

**Comment by ziegm** [comment]
To remain congruent with CDA, we should leave it that way in CH EMED, as it is only textually described in FHIR. In addition, we have described [split dosing](https://build.fhir.org/ig/hl7ch/ch-emed/dosage.html#structured-dosage---split-dosing) in CH EMED in this way and illustrated it with examples.

@pjolo 
If you agree, please close the issue.

**Comment by pjolo** [comment]
I agree with it.
