### ISSUE TITLE
Mapping of the author of the medical decision in the Medication List document (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#113]
In order to be able to map the author (person/organization) of the medical decision (incl. timestamp) in the Medication List document, adjustments are required in the referenced resources (MedicationStatement (MTP), MedicationDispense, MedicationRequest, Observation) (analogous to what was already done for the [MedicationStatement Card](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-card.html)).

See also documentation here:
- https://docs.google.com/document/d/19rjxybOfhmCo8xCHKtUARsapZqokHE1_VP9jObressY/edit?usp=sharing
- https://docs.google.com/spreadsheets/d/1IBUy4QDELjJ2YeepeC1wv0elxP99QKOUiKgzmg7fBhQ/edit?usp=sharing

**Comment by ziegm** [comment]
Necessary adjustments in branch authors - add following elements:
* [Observation]()
   * ch-emed-ext-documentauthor 0..1
   * performer 0..1
* [MedicationDispense]()
   * ch-emed-ext-documentauthor 0..1
   * performer.actor 0..1
* [MedicationRequest]()
   * ch-emed-ext-documentauthor 0..1
   * performer 0..1
* [MedicationStatement]() 
   * ch-emed-ext-documentauthor 0..1
   * informationSource 0..1
   * _move defined elements in differential form MedStatCard to MedStat, so it is also valid for MedStatMTP ([comparison MedStats](https://docs.google.com/spreadsheets/d/1bBktYc8WbVg-AspHc4bCqD18g8-QIcsToPd4YtEATS4/edit?usp=sharing))_

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:

**Update profiles:**
* [Observation](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-observation.html)
   * extension:authorDocument 0..1
   * performer 0..1
* [MedicationDispense](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationdispense.html)
   * extension:authorDocument 0..1
   * performer.actor 0..1
* [MedicationRequest](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationrequest.html)
   * extension:authorDocument 0..1
   * performer 0..1
* [MedicationStatement (basic)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationstatement.html) 
   * extension:authorDocument 0..1
   * informationSource 0..1
   * _move already defined elements in differential from MedStatCard to MedStat (basic), so it is also valid for MedStatMTP ([comparison MedStats](https://docs.google.com/spreadsheets/d/1bBktYc8WbVg-AspHc4bCqD18g8-QIcsToPd4YtEATS4/edit?usp=sharing))_

**Guidance in IG:**
* Use cases to illustrate different cases for the different documents, see tab [Different Authors](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/different-authors.html) under Guidance

**Comment by pjolo** [comment]
Checked and for me everything is ok.

**Comment by ziegm** [comment]
Close issue, will be merged to master with merging stu3ballotresolution branch
