### ISSUE TITLE
Medication Card document with different authors (document/section/entry) - JSON Representation (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#114]
ch.fhir.ig.ch-emed#2.1.0 /Bundle-MedicationCard-DifferentAuthors.json.html

Adjust example with the following:
1. Use PractitionerRole instead of Practitioner and Organization as separate examples
2. Adapt the http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-documentauthor.html that it follows the pattern for ch-ext-time, proposition:

```xml
     <extension url="http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-documentauthor">
          <valueReference>
            <extension url="http://fhir.ch/ig/ch-core/StructureDefinition/ch-ext-epr-time">
              <valueDateTime value="2019-02-12T11:00:00+01:00"/>
            </extension>
            <reference value="urn:uuid:cfa23b58-502f-46ca-8f78-99b99ed9ea35"/>
          </valueReference>
        </extension>
````

This would follow the same approach as for the author (which is of type Reference):

```xml
        <author>
          <extension url="http://fhir.ch/ig/ch-core/StructureDefinition/ch-ext-epr-time">
            <valueDateTime value="2022-08-10T13:35:06+00:00"/>
          </extension>
          <reference value="urn:uuid:f7d427f5-b436-4088-a7c3-764f53f47ea6"/>
        </author>
```

Oliver Egger, ahdis

**Comment by ziegm** [comment]
Updates:
* Simplification of CH EMED Extension Document Author: [proposal]() ([current version]())
* Limit References to PractitionerRole for following elements ([Extension Represented Organization]() not necessary anymore):
   * MedicationStatement.informationSource
   * MedicationDispense.performer.actor
   * MedicationRequest.performer
   * Observation.performer
   * All documents: Composition.section:author
      * fix slicing error (allow more than the time extension)

**Comment by ziegm** [comment]
Updates:
* Usage of CH Core Extension 'Author of the content' (removal of CH EMED Extension 'Document Author')
* Limit References to PractitionerRole for following elements ([CH EMED Extension Represented Organization](https://fhir.ch/ig/ch-emed/2.1.0/StructureDefinition-ch-emed-ext-representedorganization.html) not necessary anymore):
   * [MedicationStatement](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationstatement.html) -> informationSource 0..1
   * [MedicationDispense](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationdispense.html) -> performer.actor 0..1
   * [MedicationRequest](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationrequest.html) -> performer 0..1
   * [Observation](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-observation.html) -> performer 0..1
* Limit References to PractitionerRole | Patient | RelatedPerson (analogue to Composition.author, but without Device)
   * All documents: Composition.section:author (e.g. [Composition List](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-composition-medicationlist.html))
      * fix slicing error (allow more than the time extension)
* Update example [Medication Card document with different authors (document/section/entry)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/Bundle-MedicationCard-DifferentAuthors.xml.html)

**Comment by pjolo** [comment]
For MedicationDispense [performer.actor](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationdispense-definitions.html#MedicationDispense.performer.actor) is 1..1 not 0..1. This had to be adjusted

**Comment by ziegm** [comment]
If it is a PRE document, the author of the medical decision is mapped in Composition.author or Composition.section.author.
http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/different-authors.html#elementary-documents-mtp-pre-dis-padv

[MedicationRequest profile:](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationrequest.html) _"LIST: The author and her/his organization of the medical decision, see also 'Guidance - Different Authors'"_

It is only required if it's in a LIST. We need the same profile for LIST and PRE.
@oliveregger @pjolo :  should we introduce seperate profiles (MedStat, MedDisp, MedReq, Obs) for LIST, to be more clear and support a better validation?

**Comment by oliveregger** [comment]
yes why not.

**Comment by ziegm** [comment]
> For MedicationDispense [performer.actor](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationdispense-definitions.html#MedicationDispense.performer.actor) is 1..1 not 0..1. This had to be adjusted

Telco with Patrick, 20.10.2022
=> needs to be adjusted to 0..1
* decision to support different profiles for LIST vs. DIS/PRE/MTP/PADV

**Comment by ziegm** [comment]
@pjolo 
Please review the additional profiles for the medication list document:
* [MedicationStatement (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medicationstatement-list.html)
* [MedicationRequest (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medicationrequest-list.html)
* [MedicationDispense (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medicationdispense-list.html)
* [Observation (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-observation-list.html)

**Comment by pjolo** [comment]
Checked and is ok for me
