### ISSUE TITLE
Anwendungsfall 2-2: PADV Kommentar/Commentaire  (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#118]
ch.fhir.ig.ch-emed#2.1.0 /usecase-german.html
ch.fhir.ig.ch-emed#2.1.0 /usecase-french.html

Kommentar zur Medikation: 2-2 Pharmaceutical Advice document
Commentaire relatif à la médication: 2-2 Pharmaceutical Advice document

At step 2-2, the medication is stopped using PADV CANCEL. The title "Kommentar zur Medikation" (=Composition.title) is confusing in this use case step as there is also a PADV COMMENT.

Proposed change: Pharmazeutischer Ratschlag/Conseil pharmaceutique

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Telco mit Patrick, 20.10.2022:
* Anpassen im Use Case
* Vorschlag okay

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* [Use Case in German](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue118_comment-uc/usecase-german.html#kontrolle-hausarzt): Pharmazeutischer Ratschlag: 2-2 Pharmaceutical Advice document (CANCEL)
* [Use Case in French](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue118_comment-uc/usecase-french.html#contr%C3%B4le-par-le-m%C3%A9decin-de-premier-recours): Conseil pharmaceutique: 2-2 Pharmaceutical Advice document (CANCEL)

**Comment by pjolo** [comment]
Checked and everything is ok
