### ISSUE TITLE
CH EMED Observation - Mappings (Michaela Ziegler, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#119]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-observation-mappings.html

Update the mapping to CDA for element Observation.note:
* current: note.text = .text
* update: note.text = COMMENT: .text. OK/CHANGE/REFUSE/CANCEL/SUSPEND: .entryRelationsship where [hl7:act [hl7:templateId [@root='2.16.756.5.30.1.1.10.4.2']]]

Correct the mapping to CDA for element Observation.extension (medicationStatementChanged):
* current: .observation.entryRelationship. ...
* update: .entryRelationship. ... (.observation is otherwise listed twice)

Michaela Ziegler, ahdis

**Comment by ziegm** [comment]
@pjolo 
The [mapping](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-observation-mappings.html#mappings-for-cda-r2-http-hl7-org-v3-cda) was adjusted before the decision regarding CDA. It will now no longer be necessary and will be removed as part of the CDA issue (#150). Is that okay?

**Comment by pjolo** [comment]
This is okay for me
