### ISSUE TITLE
Mapping AnnotationComment and Patient Instructions to MedicationStatement for the MedicationCard? (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-emed#120]
We noticed a problem with the mapping with the 

https://github.com/ahdis/ch-emed-pmp/wiki/Test-Cases#21-padv-change

2.1.1 CH EMED - UC Step 1-1 and PADV description: 

change posology[1-1-MTP-Triatec](http://build.fhir.org/ig/hl7ch/ch-emed/Bundle-1-1-MedicationTreatmentPlan.json.html): 0.5-0-0-0

[1-x-PADV-Triatec](http://build.fhir.org/ig/hl7ch/ch-emed/Bundle-PharmaceuticalAdvice-ChangeDosage.json.html): 1-0-0-0

Currently the comment Dosierungsänderung: "Morgens 1 Tablette anstatt 0.5 Tablette"
is not mapped in the MedicationStatment.note. (it is in the CDA set as an Annotation Comment, visible in the pdf).

MedicationStatement.note is currently mapped from PatientInstructions. Should we change that the mapping for PatientInstructions is done in dosage.patientInstruction?

**Comment by ziegm** [comment]
depending on the decision, this has an influence on this issue: #116

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* Change mapping for patient instruction from '.note' to 'Dosage.patientInstruction' to be able to map the annotation comment in the Medication Card document to 'MedicationStatemtent.note'.
   * [Dosage nonstructured](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-dosage-nonstructured.html) 
   * [Dosage structured](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-dosage-structured.html)
   * [MedicationStatement (Card)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationstatement-card.html)

**Comment by pjolo** [comment]
checked and ready to merge

**Comment by ziegm** [comment]
Close issue, will be merged to master with merging stu3ballotresolution branch
