### ISSUE TITLE
Introduction - remove reference to eHealth Suisse (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#123]
ch.fhir.ig.ch-emed#2.1.0 /

This implemenation guide is based on the CDA-CH-EMED eMedication ART-DECOR® specification which has been published by eHealth Suisse.

-> remove which has been published by eHealth Suisse. 

Because it should be now published under the governace of hl7.ch.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
@ziegm Maybe we need even to remove the ART-DECOR references and say that the FHIR specification is derived from the IHE Pharmacy Content profiles.

**Comment by ziegm** [comment]
[Introduction](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue123_introduction/index.html)

**Comment by pjolo** [comment]
Ok for me
