### ISSUE TITLE
Unstructured dosage: allow start and end date on dosage (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#127]
Allow start and end date on unstructured dosage.
Dosage.timing.repeat.boundsPeriod.start
Dosage.timing.repeat.boundsPeriod.end

**Comment by qligier** [comment]
It would prefer to merge the three dosage types and relax the rules there. The three dosage types separation came from CDAs, it could be changed and simplified now.

**Comment by ziegm** [comment]
@oliveregger / @qligier / @pjolo 
* [Profile with dosage slices](http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/StructureDefinition-ch-emed-medicationdispense.html)
* [Dosage guidance](http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/dosage.html)

**Comment by ziegm** [comment]
Feedback from @qligier via email (10.11.2022): He does agree with the proposed dosage changes.

**Comment by oliveregger** [comment]
10.2.2: The narrative dosage instructions is represented in the Dosage.textelement. -> space needs to be added for  Dosage.text element

could we add example which shows normal dosage with structured and narrative (10.2.3)?

Split Dosing
 e.g. route of administration, is mapped in the first dosage element.
-> can we list here all mustSupport elements including narrative text to make it more clear?

http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/StructureDefinition-ch-emed-medicationstatement-card.html
dosage does not show the slices as http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/StructureDefinition-ch-emed-medicationstatement-card.html?

**Comment by ziegm** [comment]
The first three points are fixed. 
The fourth point is a "problem" that not everything is displayed in the 'Differential Table' as in the 'Key Elements Table'. Will be left like this, after discussion with Oliver.

**Comment by pjolo** [comment]
I agree with the changes

**Comment by ziegm** [comment]
Merged the branch 'Dosage'
