### ISSUE TITLE
Structured Dosage discussion (Projectathon Meeting, 14.9.2022)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#130]
ch.fhir.ig.ch-emed#2.1.0 /dosage.html

Cerner Feedback from implementation at projectathon: 

2 scenarios where we don't can send the timing but would like to have structured
- as needed (ev. an an option with a max number for a day) 
- we can't match it to the timing events but we still can structure the rest like route and doesQuantityNote

Projectathon Meeting, 14.9.2022

**Comment by ziegm** [comment]
Simplification/enhancement of the [dosage](http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/StructureDefinition-ch-emed-dosage.html) makes these above-mentioned cases possible.

@pjolo please review the updates

(Cerner is informed via email)

**Comment by rhallowell** [comment]
If I understand what I read via the link to dosage provided, then I think this works.

**Comment by ziegm** [comment]
@rhallowell you could give me one or two "real" examples and we could add them to the IG?

**Comment by rhallowell** [comment]
How about:   
Nitrostat 1 tab take as needed for chest pain, max of 3 tabs in 15 minutes

**Comment by ziegm** [comment]
To be discussed @ telco with @pjolo :

To map Cerner's example, we need other elements of dosing that have not been described in CH EMED before. How do we deal with this topic?
* [Example](http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/MedicationStatement-AsNeededWithMaxDose.json.html)
* [Dosage profile](http://build.fhir.org/ig/hl7ch/ch-emed/branches/dosage/StructureDefinition-ch-emed-dosage.html)

Elements that are not described so far:
   * doseAndRate.rate[x]
   * **maxDosePerPeriod**
   * maxDosePerAdministration
   * maxDosePerLifetime

**Comment by ziegm** [comment]
@pjolo 
Please review the changes

**Comment by pjolo** [comment]
The changes are ok for me.
