### ISSUE TITLE
Clearification of description for extensions id & externalDocumentId (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#131]
extension:id = ID of the Medication Treatment Plan document => Identifier of the original MedicationStatement
extension:externalDocumentId = ID of the external document => Identifier of the original document

for all these extensions:
http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-treatmentplan.html
http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-pharmaceuticaladvice.html
http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-prescription.html
http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-dispense.html

**Comment by ziegm** [comment]
[CH EMED Extension Dispense](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-dispense.html)
 Extension to reference the medication dispense

Update the description according to the others:
Extension to represent the reference to the Medication Dispense document

**Comment by ziegm** [comment]
Related Issue: https://github.com/hl7ch/ch-emed/issues/156 (point 1 & 2)

**Comment by ziegm** [comment]
Extension: Extension to reference an external medication dispense

extension:id =  Identifier of the referenced MedicationStatement
extension:externalDocumentId =  Identifier of the original document

**Comment by ziegm** [comment]
Vorschlag wie an Telco vom 10.11.2022 PJ/OE/MZ besprochen:

[Extensions](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue131_extension-description/extensions.html):
- http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue131_extension-description/StructureDefinition-ch-emed-ext-treatmentplan.html
- http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue131_extension-description/StructureDefinition-ch-emed-ext-pharmaceuticaladvice.html
- http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue131_extension-description/StructureDefinition-ch-emed-ext-prescription.html
- http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue131_extension-description/StructureDefinition-ch-emed-ext-dispense.html

**Comment by ziegm** [comment]
@pjolo 
As discussed yesterday at the telco (PJ/OE/MZ), please review the changes.

**Comment by pjolo** [comment]
Ok issue can be closed
