### ISSUE TITLE
Practitioner.address should not be required (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#132]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-practitioner.html

According to the mapping table (https://docs.google.com/spreadsheets/d/1Ui3NGFE2I8yiOlHELk-B0Pke2l9-Jbe5BTeYOnS8-uE/edit#gid=0) the required address should be on the Organization and not on the Practitioner.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Gemäss der Mappingtabelle (Ausschnitt unten) wird der Behandelnde mittels Practitioner und Organization abgebildet. 
![image](https://user-images.githubusercontent.com/32767151/195297075-c49fefc9-953f-4fdc-b421-0208e9a4d238.png)
Das Minimal Data Set (IPAG) hat Elemente in beiden Ressourcen. Aktuell ist es jedoch möglich, bei Composition.author nur den Practitioner anzugeben (daher stammt wohl die Pflichtangabe der Adresse).

Änderungsvorschlag:
* Composition.author -> Reference(CH EMED PractitionerRole | Device | CH Core Patient EPR | RelatedPerson)
   * CH EMED Practitioner & CH Core Organization EPR entfernen
* CH EMED PractitionerRole
   * .organization 1..1 anstatt 0..1
   * .organization -> Reference(CH EMED Organization) anstelle CH Core Organization EPR
* CH EMED Organization
   * .address -> Minimumkardinalität = 1, MS 
* CH EMED Practitioner
   * .address -> weder Kardinalität noch MS im Differential definieren  
* Beispiele anpassen: PractitionerRole anstelle Practitioner & Organization verwenden
* Hinweis: Der Einsatz von lediglich PractitionerRole wurde im Rahmen des [Issues #113](https://github.com/hl7ch/ch-emed/issues/113) bereits angedacht, siehe [Extension Document Author](http://build.fhir.org/ig/hl7ch/ch-emed/branches/authors/StructureDefinition-ch-emed-ext-documentauthor.html). Diese beiden Issues können aber unabhängig voneinander betrachtet werden.

**Comment by ziegm** [comment]
Telco with Patrick, 20.10.2022:
Decision to use PractitionerRole (remove Organization/Practitioner in profile/examples)
