### ISSUE TITLE
PRE: Multiple authors for medical decision? (Thomas Stutz, HCI Solutions AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#133]
ch.fhir.ig.ch-emed#3.0.0 /medication-prescription-document.html

Has anyone a use case for multiple authors for medical decision (MedicationPrescription resources with different performer) inside one prescription document? I propose, if there is a difference between document author and performer (author medical decision), put the performer into the composition section (only one possible per prescription document) and not on the MedicationPrescription.

Thomas Stutz, HCI Solutions AG

**Comment by qligier** [comment]
About multiple performers:
A single PRE document should contain a single "performer" that takes legal responsibility for it (and may sign it). If there are multiple performers, multiple PRE documents should be created.

About the difference of document and composition authors:
The composition author is the author of the medical decision (the performer), while the document author is the person who processed the content (usually the performer, but it could be an assistant or other roles).

**Comment by ziegm** [comment]
This has already been described under Guidance - Different Authors, see [here](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/different-authors.html#overview-different-levels) for PRE.
To draw attention to this in the profiles themselves, the following note has been added to the description:
**..., see also description under 'Guidance - Different Authors'**

Done for all documents in Composition.section.author and Entry.extension:authorDocument/performer (e.g. Composition (PRE), MedicationRequest).

**Comment by ThomasStutz** [comment]
The solutions looks good to me.

**Comment by pjolo** [comment]
Checked and for me everything is ok.

**Comment by ziegm** [comment]
Close issue, will be merged to master with merging stu3ballotresolution branch
