### ISSUE TITLE
CH EMED Observation: add slice  (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#134]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-observation.html

add slice for this extension: http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-pharmaceuticaladvice
(based on https://github.com/hl7ch/cda-fhir-maps/issues/53)

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
I withdraw this motion, this does not belong in the exchange format, it is a consideration that is being put to the Device that is creating a Medication List.

**Comment by ziegm** [comment]
@pjolo: Is it okay to close the issue?

**Comment by pjolo** [comment]
Yes, it is ok for me if this problem is closed.
