### ISSUE TITLE
Medication Card document (Marcel Hanselmann, HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#135]
ch.fhir.ig.ch-emed#2.1.0 /medication-card-document.html

broken link: http://fhir.ch/ig/ch-emed/Bundle-2-7-MedicationCard-UUIDfulUrl.json.html

Marcel Hanselmann, HL7

**Comment by ziegm** [comment]
@pjolo 
Please review the changes and if approved, please merge the [PR](#145) and close the issue.
* [Fixed link](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue135_brokenLink/Bundle-2-7-MedicationCard-UUIDfullUrl.json.html) on page [Medication Card document](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue135_brokenLink/medication-card-document.html) 
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue135_brokenLink/changelog.html)

**Comment by pjolo** [comment]
Checked and ok for me
