### ISSUE TITLE
Medication Prescription document (Marcel Hanselmann HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#137]
ch.fhir.ig.ch-emed#2.1.0 /medication-prescription-document.html

Das ist wohl das e-Rezept, bei LOINC 'Document used to prescribe drugs' genannt. Ich würde das klarer formulieren, damit es vom Treatment Plan Document unterscheidbar ist. z.Bsp. 'The Document is used to inform the Pharmacy or other drug dispensing place, which drugs the patient needs, the dosage, period of intake etc.' 

Marcel Hanselmann HL7

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):

**Comment by pjolo** [comment]
MH: Bevorzugt die Beschreibung 'The Document is used to inform the Pharmacy or other drug dispensing place, which drugs the patient needs, the dosage, period of intake etc.' zu verwenden.

**Comment by ziegm** [comment]
29.11.2022 Telco PJ/OE/MZ:
Aktuell wird die Beschreibung von IHE verwendet. Diese sollte höchstens für Schweizer Verhältnisse präzisiert werden.
IHE PRE: The Community Prescription Document Profile (PRE) describes the content and format of a Community Prescription document generated during the process in which a health care professional (in most cases, but not necessarily always, a medical specialist or a general practitioner) decides that the patient needs medication

Vorschlag: Bei der bisherigen Beschreibung bleiben.

**Comment by pjolo** [comment]
Adjustment ok for me and Marcel informed about adjustment.
