### ISSUE TITLE
Medication List document (Marcel Hanselmann HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#138]
ch.fhir.ig.ch-emed#2.1.0 /medication-list-document.html

Für mich ist die Aufgabe von List document nicht klar. 
Es gibt im klinischen Alltag ein extrem wichtiges Dokument, das wir "Medi-Karte", "Medi-Liste" oder ähnlich genannt haben. Es enthält knappe Informationen wie Namen von Arzt und Patient, Datum der Ausstellung, und eine Liste der aktuell eingenommenen Medikamente mit Dosierung und Tagesplan. Und diese Mediliste entspricht LOINC Code 56445-0 "Medication summary". Alle anderen Einträge, wie Medication Treatment Plan, Medication Prescription, Medication Dispense and Pharmaceutical Advice entries haben darauf nichts zu suchen!
Oder ist Medication Card document dafür vorgesehen, dessen Typ ebenfalls loinc.org#56445-0 "Medication summary" ist. 
Wozu braucht es dann das Medication List Document? Sollte das die Medication History sein. Doch auch gäbe es eine sinnvollere Lösung: Liste aller Treatment Plan Document über die Zeit, enthaltend Medikament und Dosierung, sowie Beginn und Ende. Damit würde der Arzt einen raschen Überblick über die vergangene und aktuelle Medikation erhalten. 

Marcel Hanselmann HL7

**Comment by qligier** [comment]
The Medication List document allows merging multiple document content (MTP, PRE, DIS) into a single one and do a single retrieve transaction. The document is usually generated on-demand with the PHARM-1 transaction, specifying constraints on which entries are added to the PML.

Its use is really distinct from the Medication Card.

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):

**Comment by pjolo** [comment]
Klare trennung von Medication Card und Medication List (LOINC-Code).
