### ISSUE TITLE
Medication Card document (Marcel Hanselmann HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#139]
ch.fhir.ig.ch-emed#2.1.0 /medication-card-document.html

Vielleicht ist mit Medication Card document LOINC Code 56445-0 das gemeint, was wir als
Medi-Liste oder Medi-Karte bezeichnet haben, siehe den Eintrag unter Medication List document. 
Dann wäre aber die * section[=].code = http://loinc.org#10160-0 "History of medication use" fehl am Platz. 

Ich würde folgende beiden nützlichen Dokumente vorschlagen: 

Medication List document LOINC Code 10160-0 "History of medication use" für die Medication History, die aus der Summe der Treatment Plan Document über die Zeit automatisch gebildet wird.

Medication Card document LOINC Code 56445-0 "Medication summary" für die übersichtliche 'Medi-Karte', enthaltend nebst Namen von Arzt und Patient nur die aktuelle Medikation, selbstverständlich das Austellungsdatum, aber keinen unnötigen weiteren Ballast.

Marcel Hanselmann HL7

**Comment by qligier** [comment]
The CDA Medication Card does contain $lnc#56445-0 "Medication summary" and $sct#721912009 "Medication summary document (record artifact)".

https://art-decor.org/art-decor/decor-templates--cdachemed-?id=2.16.756.5.30.1.1.10.2.50&effectiveDate=dynamic

**Comment by ziegm** [comment]
[Medication List document](https://fhir.ch/ig/ch-emed/2.1.0/medication-list-document.html) and [Medication Card document](https://fhir.ch/ig/ch-emed/2.1.0/medication-card-document.html) are both based on PML as described in the document tabs.
[IHE Pharmacy Technical Framework Supplement: Community Medication List (PML)](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PML.pdf)

PML defines the following codes:
* Document code: 56445-0, LOINC, Medication summary (CH EMED: Composition.type)
* Section code: 10160-0, LOINC, History of medication use (CH EMED: Composition.section.code)

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):

**Comment by pjolo** [comment]
MH: 
Ist der Meineung, dass die Beschreibung von LOINC (56445-0) für Medication Card verwendet wird.

**Comment by ziegm** [comment]
29.11. Telco PJ/OE/MZ:
Finaler Text:
_The Medication Card document provides as complete an overview as possible of all current medications for a patient at a given point in time (such as the end of a hospitalization or other encounter). The purpose of this document is to inform the patient and clinicians (therapists, etc) of the current medication information._

Besprechung:
Die Verwendung des LOINC Textes kann nicht ohne Anpassung übernommen werden, da in der CARD auch Selbstmedikation enthalten sein kann und nicht nur "prescribed" Medication. Der Autor kann auch eine Software sein.

**Comment by ziegm** [comment]
Updated Description: [Medication Card document](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/medication-card-document.html)

**Comment by pjolo** [comment]
Adjustment ok for me and Marcel informed about adjustment.
