### ISSUE TITLE
Differentiation List - Card? (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#140]
At the moment the only possibility (?) to differentiate LIST and CARD is Composition.title (if de/fr/it/en) when the LIST only contains a MedicationStatement. Should we consider providing a clear differentiation, as there are already use cases in practice that require this differentiation?

**Comment by lpg-tech** [comment]
The medication actually only needs the following documents:
1. medication order
Medication xy / timestamp beginning / timestamp end for each medication.
It is the difference to current medication history. Important: a medication can be added ore removed (medication ends)
2. medication history: automatically generated from the sum of medication prescriptions in the EHR.
3. e-prescription: medication that the patient currently needs. Usually subset of medication list (6).
4. medication dispensing
5. feedback from pharmacist
6. medication list: All medication prescriptions whose end date has not been reached; is equivalent to loinc.org#56445-0 "Medication summary". There are all medications that the patient should currently be taking.

Medication treatment plan corresponds to medication history (2) for a single medication, hence it does not need a separate document in my opinion

Wording is to discuss (list, card, order, prescription etc.), what matters are the meanings of the documents.

**Comment by qligier** [comment]
As discussed in #139, the document code is different in PML and PMLC documents.

> Medication treatment plan corresponds to medication history (2) for a single medication, hence it does not need a separate document in my opinion

I'm uncertain whether I've understood your point, but the MTP document is much closer to 1 (a medication order from an HCP or a medication announce from the patient)

1. MTP document
2. PML document
3. PRE document
4. DIS document
5. PADV document, but not limited to the pharmacist. Feedback can come from HCPs or the patient
6. PMLC document

**Comment by lpg-tech** [comment]
Sorry, we have a different concepts. Why should we need a document that describes the medication history for a single medicament? We want to determine the temporal relationship between clinical symptoms/complaints and drug intake when we are looking for intolerances or allergies. This is a common question that should be able to be assessed comprehensively. For that reason the history should be complete and include all medicaments.

**Comment by qligier** [comment]
MTP, DIS and PADV are focused on a single medication, but PRE, PML and PMLC can include multiple treatments. What you're describing ("the history should be complete and include all medicaments") is typically the PML document.

**Comment by ziegm** [comment]
**Composition.type.code**
| Document | LOINC | SCT |
| :--- | :--- | :--- |
| **LIST** | 56445-0 Medication summary | 721912009 Medication summary document (record artifact) | 
| **CARD** | 56445-0 Medication summary | 721912009 Medication summary document (record artifact) | 
| **PRE** | 57833-6 Prescription for medication | 761938008 Medicinal prescription record (record artifact) | 
| **MTP** | 77603-9 Medication treatment plan.extended | 419891008 Record artifact (record artifact) | 
| **DIS** | 60593-1 Medication dispensed.extended | 419891008 Record artifact (record artifact) | 
| **PADV** | 61356-2 Medication pharmaceutical advice.extended | 419891008 Record artifact (record artifact) |

**Comment by ziegm** [comment]
Note: 
At the time of the initial creation of the profiles, only one coding could be mapped via patternCodeableConcept. The second coding was only represented in the examples. In the meantime this is possible (see example below), should this be added?

![image](https://user-images.githubusercontent.com/32767151/198026224-1e1e9784-6689-405a-ac20-3a57f09fe94e.png)

**Comment by qligier** [comment]
Ideally, we would find another LOINC code to distinguish between PML and PMLC and we would only use the LOINC variant, the SNOMED CT codes being the same for multiple documents, and then not so useful.

**Comment by ziegm** [comment]
[Medication List document](https://fhir.ch/ig/ch-emed/2.1.0/medication-list-document.html) and [Medication Card document](https://fhir.ch/ig/ch-emed/2.1.0/medication-card-document.html) are both based on PML as described in the document tabs.
[IHE Pharmacy Technical Framework Supplement: Community Medication List (PML)](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PML.pdf)

PML defines the following codes:

Document code: 56445-0, LOINC, Medication summary (CH EMED: Composition.type)

**Comment by ziegm** [comment]
10.11.2022 Telco PJ/OE/MZ:
@pjolo Anderer Code (LOINC/SCT) für LIST
Wir haben keine möglichen Codes bei LOINC oder SCT gefunden, ist es möglich einen Swiss Extension SCT Code zu erstellen?
Medication List document: Dokumentenbeschreibung (noch ausstehend)

**Comment by pjolo** [comment]
After internal discussion.
A new code for Medication Card will be added. The proposed code is **Medication Plan**. 
In order to reach a quick introduction, the code is proposed for SNOMED International. This means that the code will be introduced around March. If the code is rejected by SNOMED International, the code will be included in the Swiss Extension. As the Swiss Extension is currently frozen for the release, the code could not be included until the summer of 2023.

**Comment by qligier** [comment]
Thank you Patrick! At what time could we have an idea of the actual code value that would be introduced?

**Comment by pjolo** [comment]
I think we will have a first proposal by March

**Comment by qligier** [comment]
Wait, proposed to SNOMED?

The current issue the spec has is that, when you get a CH-EMED document, it's hard to determine of which type it is. The meta.profile is optional and can contain anything, the Bundle doesn't contain anything useful and the Composition only has a type with 3 unique values for 6 document types. We should have one unique Composition type per document type, and it cannot be done by adding one code to SNOMED, but adding one code to LOINC.

So what's the plan here?

**Comment by qligier** [comment]
More information about why I react to adding a new value to SNOMED CT in #178, I hope it's more clear now.

**Comment by ziegm** [comment]
Telco 12.01.2023 PJ/QL/OE/MZ:
The [proposed solution](https://github.com/hl7ch/ch-emed/issues/178#issuecomment-1369806350) is still fine.

**Comment by pjolo** [comment]
I have looked at this issue again with Pero. He made me a proposal which only SNOMED CT codes are used for LIST,CARD,PRE,MTP,DIS and PADV:

| Document| SCT|
|--------|--------|
| LIST| 721912009 Medication summary document (record artifact)|
| CARD| 736378000 Medication management plan (record artifact)|
| PRE| 761938008 Medicinal prescription record (record artifact)|
| MTP | 761931002 Medication treatment plan report (record artifact)|
| DIS| 294121000195110 Medication dispense document (record artifact)|
|PADV|423016009 Clinical statement entry (record artifact)| 

@ziegm, @qligier: Are the defined codes for you ok?

**Comment by qligier** [comment]
For PADV documents, I am unsure if changing from _Record artifact_ to _Clinical statement entry_ is a good idea. Otherwise it seems good!

But, since this code is used as DocumentEntry.typeCode, the codes 736378000, 761931002, 294121000195110 (and 423016009?) should be added to the value set [DocumentEntry.typeCode (beta version)](https://art-decor.org/art-decor/decor-valuesets--ch-epr-?id=2.16.756.5.30.1.127.3.10.1.27&effectiveDate=2021-05-04T11:13:43). Would that be OK with Pero?

**Comment by ziegm** [comment]
Thanks @pjolo for the suggestion and @qligier for the feedback! 
I fully agree with Quentin's feedback.

**Comment by ziegm** [comment]
@pjolo any updates on this topic?

**Comment by pjolo** [comment]
@qligier @ziegm Why do you think that the change from Record artifact to Clinical statement entry is not a good idea? For me it is not a problem we can leave it on Record artifact. So we would have the following codes:

Document | SCT
-- | --
LIST | 721912009 Medication summary document (record artifact)
CARD | 736378000 Medication management plan (record artifact)
PRE | 761938008 Medicinal prescription record (record artifact)
MTP | 761931002 Medication treatment plan report (record artifact)
DIS | 294121000195110 Medication dispense document (record artifact)
PADV | 419891008 Record artifact (record artifact)


Pero will add the codes this afternoon in the value set DocumentEntry.typeCode (beta version)

**Comment by qligier** [comment]
Because a PADV can be issued by a patient or a pharmacist, they don't issue "clinical statements". Also, I'm not sure a GP is considered a clinical environment.
For these reasons, "Record artifact" is a more fitting code, although overly generic.

**Comment by ziegm** [comment]
> @qligier @ziegm Why do you think that the change from Record artifact to Clinical statement entry is not a good idea? For me it is not a problem we can leave it on Record artifact. So we would have the following codes:
> 
> Document	SCT
> LIST	721912009 Medication summary document (record artifact)
> CARD	736378000 Medication management plan (record artifact)
> PRE	761938008 Medicinal prescription record (record artifact)
> MTP	761931002 Medication treatment plan report (record artifact)
> DIS	294121000195110 Medication dispense document (record artifact)
> PADV	419891008 Record artifact (record artifact)
> Pero will add the codes this afternoon in the value set DocumentEntry.typeCode (beta version)

Can I update the examples with those codes above? 
And we only change the CARD document with the new SCT code and use LOINC for the others, like we discussed, correct?

**Comment by qligier** [comment]
> LIST: change patternCodeableConcept to SCT code instead of LOINC in profile

Does that mean the patternCodeableConcept would be on LOINC codes for MTP, PRE, DIS and PADV, and on SCT for PML and PMLC? Maybe we should set the SCT codes as primary ones for all types here, and add the LOINC codes as translation?

**Comment by ziegm** [comment]
@pjolo @qligier please review the changes:
Changes for Composition.type (see [ci-build](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue140/index.html)):
* ALL DOCS: add constraints in profiles to check the second coding (LOINC)
* CARD/MTP/DIS: update profiles and examples with new SCT codes
* update change log

-> TODO: https://github.com/hl7ch/ch-emed/issues/224

**Comment by qligier** [comment]
I can't find 294121000195110 in the SCT browser, is it a Swiss extension? If so, should we apply #224 to it now?

**Comment by ziegm** [comment]
I guess it will be in the next release (@PeroGrgic )?
I'm working on #224

**Comment by PeroGrgic** [comment]
Hi, 
294121000195110 will be in the next release of the Swiss extension.

**Comment by PeroGrgic** [comment]
> 

The next release is on the 7th of June.

**Comment by pjolo** [comment]
The adjustments are good
