### ISSUE TITLE
GTIN should be an identifier and not a code (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#142]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-medication.html

The GTIN should be an Identifier and not a code. IPS does also not declare a the GTIN as code.
identifier: Business identifier for this medication.
see http://hl7.org/fhir/R4/resource.html#identifiers
"Each representation carries common identifiers that identify the underlying concept (also called "real world entity") consistently across all contexts of use. This is known as the business identifier, and is found in the identifier element, which has the type Identifier."

Roeland Luykx (RALY GmbH)

**Comment by qligier** [comment]
The documentation speaks about the resource identifier `id`. The GTIN is the `code`, not the resource identifier and should be a CodeableConcept.

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Medication-uv-ips.html

IPS uses also code for the medication, not explicitly mentioning GTIN, but that's what we use currently for coding medication (the GTIN does not identify the medication itself in my view, you can multiple medication's within the system with the same GTIN and different batch numbers).

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):
