### ISSUE TITLE
CH EMED Medication (François von Kaenel, Berner Fachhochschule)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#143]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-medication.html

In CH EMED Medication, the GTIN is defined to be used for coding the medication.
Each package size has a different GTIN, i.e. for ASPIRIN CARDIO Filmtabl 100 mg:

7680517950680 for Blister 28 Stk
7680517950406 for Blister 90 Stk
7680517950697 for Blister 98 Stk

Wouldn't it be practical to also code the product (same code for all packages)?

François von Kaenel, Berner Fachhochschule

**Comment by qligier** [comment]
Yes, but in which system?

**Comment by ziegm** [comment]
IPAG does not provide this information for the exchange format. What would be a possible use case where this information is needed in the exchange format?
The information is mapped in the context of IDMP (identification of medicinal products) -> MedicinalProductDefinition.identifier (see [here](http://hl7.org/fhir/R4B/medicinalproductdefinition-mappings.html)).

**Comment by ziegm** [comment]
Telco 24.11.2022 (PJ/RL/FvK/MH/OE/MZ):
