### ISSUE TITLE
Composition.title: typo in description (Michaela Ziegler, ahdis ab)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#144]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-composition-medicationtreatmentplan.html

 in talian = > in italian

Michaela Ziegler, ahdis ab

**Comment by ziegm** [comment]
@pjolo 
Please review the fixed typos in all Composition.title/Composition.section.title:
http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue144_typo/index.html

**Comment by pjolo** [comment]
Checked and all ok for me
