### ISSUE TITLE
Add ATC coding in Medication

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#149]
CDAs have added support for the ATC code. Currently, only the GTIN slice is present in Medication.

**Comment by ziegm** [comment]
It is not in the minimal data set of IPAG, but it is listed for Non-Swiss products, see [here](https://docs.google.com/spreadsheets/d/1Ui3NGFE2I8yiOlHELk-B0Pke2l9-Jbe5BTeYOnS8-uE/edit#gid=0). 
IPS does support ATC, see [here](http://hl7.org/fhir/uv/ips/StructureDefinition-Medication-uv-ips.html).

We could add an additional slice for ATC, see proposal:
* [Medication profile](http://build.fhir.org/ig/hl7ch/ch-emed/branches/149_atc/StructureDefinition-ch-emed-medication.html)
* [Example with ATC (foreign product)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/149_atc/Medication-MedicationWithATC.html)

**Comment by ziegm** [comment]
12.01. PJ/QL/OE/MZ
* add it to the profile

**Comment by ziegm** [comment]
@pjolo 
Please review the changes as mentioned [above](https://github.com/hl7ch/ch-emed/issues/149#issuecomment-1372320056).

**Comment by qligier** [comment]
Looks good to me!

**Comment by pjolo** [comment]
For me, the changes are ok
