### ISSUE TITLE
Mapping between CDA and Bundle/Composition

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#157]
There are some inconsistencies in the "Mapping to CDA" section of Bundles and Compositions.

For example, the CDA id is mapped to Bundle.identifier and the setId to Composition.identifier. That would imply the Bundle and Composition shall use the same identifier (as the id and setId are the same for the first version of a document). Is it allowed? Is it needed any more?

The CDA effectiveTime is mapped both from Bundle.timestamp and Composition.date.

The CDA languageCode is mapped from the Composition. Wouldn't the Bundle.language be more coherent?

**Comment by ziegm** [comment]
@qligier 
We would drop the mapping. Can we close the issue then?

**Comment by oliveregger** [comment]
The current CH Core EPR profiles require bot version dependent [Bundle.identifier](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationtreatmentplan.html) and version independent [Composition.identifier](http://fhir.ch/ig/ch-core/2.1.0/StructureDefinition-ch-core-composition-epr.html). Does that help to clarify which one to use?

**Comment by oliveregger** [comment]
> So, for the first version, they're equal, and the Bundle.identifier shall change for future versions?
could change for future versions.

>But what's the difference between Bundle.timestamp and Composition.date? Both are described as "The document's creation date and time", and the concept of version independent date is a bit weird.


see http://hl7.org/fhir/composition-definitions.html
Composition.dateTime is used for tracking, organizing versions and searching. Note that this is the time of authoring. When packaged in a document, [Bundle.timestamp](http://hl7.org/fhir/bundle-definitions.html#Bundle.timestamp) is the date of packaging.

**Comment by ziegm** [comment]
@pjolo
FYI: I close this issue and ask for review through issue 150
