### ISSUE TITLE
On the use of meta profile(s)

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#158]
The structure definitions don't specify the meta profile to use, but examples usually specify it. Is it optional or mandatory?

**Comment by qligier** [comment]
Okay, thank you!
It's unfortunate because profiles would allow to easily extend HAPI resources.

**Comment by oliveregger** [comment]
why do you need to extend HAPI resources? with a profile you could make a facade/interface to the base resource to get easier getters and setters, but this would be still possible even if the profile is not declared (from the toplevel document, you could create the interface what you expect). validation beforehand would then ensure that the data is conforming.

**Comment by qligier** [comment]
The goal is to provide a convenient API, extending what HAPI is providing.
Currently, I see four options:
- Using `parser.parseResource(resourceType, string)`: it allows specifying the document extended type, but I see no option to specify types of inner resources (e.g. the composition).
- Using `context.setDefaultTypeForProfile(profile, type)`: does exactly that, but requires a profile in all extended resources.
- Using `parser.setPreferTypes(preferTypes)`: also allows extending all types but a single time, it means having a single parser per document type, and it would not work with PML documents I guess (except if HAPI can distinguish between CHEMEDMedication and CHEMEDMedicationMedicationDispense).
- Using facades/decorators, it doesn't use HAPI mechanisms but feels more hacky, both APIs are separated.

**Comment by qligier** [comment]
Yes, implementers are responsible to properly configure parsers/validators. No constraints on meta.profile.
