### ISSUE TITLE
CH-Core: use EPR or non-EPR structure definitions?

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#159]
In CH EMED Medication Treatment Plan Document, the patient reference is of type CHCorePatient.
In CH EMED Medication Treatment Plan Composition:
- author is CHCorePatientEPR
- subject is CHCorePatientEPR
- informationRecipient is CHCorePatient

Which one should we use, the EPR or non-EPR version? Same question for CHCorePractitionerRole vs CHCorePractitionerRoleEPR (both are used).

**Comment by ziegm** [comment]
You can use the version (EPR or non-EPR) which is specified in the profile.

The EPR profiles are used at places where the data is in the context of the EPR document, e.g. [CH Core Patient EPR](https://build.fhir.org/ig/hl7ch/ch-core//StructureDefinition-ch-core-patient-epr.html):
"_Core patient definition in the context of the electronic patient record (EPR). It is used to include the patient in an EPR document (referenced in Composition/DocumentReference)._"
The InformationRecipient has not the same requirements, therefore it isn't so strict. CH Core Patient EPR is based on CH Core Patient.

**Comment by qligier** [comment]
ch-emed uses the EPR version is some places and the non-EPR in others. I guess it should only use the non-EPR version?

I'm using the EPR version everywhere downstream.

**Comment by ziegm** [comment]
Both are used in CH EMED, e.g.:
Composition.subject -> EPR
Composition.informationRecipient -> non-EPR
But these things are defined in CH Core and CH EMED only derives the profiles from there.

**Comment by qligier** [comment]
Ok, you want to bind ch-emed to the EPR restrictions? In that case, this can be closed.
