### ISSUE TITLE
missing experimental/description elements

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#160]
new IG publisher warning -> add element to terminology resources

- `The ShareableCodeSystem profile says that the experimental element is mandatory, but it is not present. Published code systems SHOULD conform to the ShareableCodeSystem profile`
- `The ShareableCodeSystem profile says that the description element is mandatory, but it is not present. Published code systems SHOULD conform to the ShareableCodeSystem profile`

**Comment by ziegm** [comment]
@pjolo 
Please review the update:
* added elements (experimental, description) to codesystems, see [commit](https://github.com/hl7ch/ch-emed/commit/0a141c1b776591fa517488eef91e5d178a3a0391)
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

@oliveregger 
Could you please adjust the Art-Decor import to generate these two elements next time?

**Comment by pjolo** [comment]
Checked and good for me

**Comment by ziegm** [comment]
2.16.756.5.30.1.127.77.4.11.2

**Comment by oliveregger** [comment]
fixed xslt mapping
