### ISSUE TITLE
include HTML fragments

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#161]
<html>
<body>

1 | warning | The HTML fragment 'ip-statements.xhtml' is not included anywhere in the produced implementation guide
-- | -- | --
2 | warning | The HTML fragment 'cross-version-analysis.xhtml' is not included anywhere in the produced implementation guide
3 | warning | The HTML fragment 'dependency-table.xhtml' is not included anywhere in the produced implementation guide
4 | warning | The HTML fragment 'globals-table.xhtml' is not included anywhere in the produced implementation guide

</body>
</html>

**Comment by ziegm** [comment]
@pjolo 
Please review the update: 
* 4 new sections
   * [IP Statements](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/index.html#ip-statements)
      * merged the previous section Copyright into new section IP Statements
   * [Cross Version Analysis](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/index.html#cross-version-analysis)
   * [Dependency Table](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/index.html#dependency-table)
   * [Globals Table](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/index.html#globals-table)
    
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

**Comment by pjolo** [comment]
Checked and all good for me
