### ISSUE TITLE
Cardinality of composition type coding

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#163]
In compositions, the type coding has a cardinality of 1..*, while its value is fixed to `$sct#419891008`. It should be set to 1..1, or a slice should be created to allow other codes.

**Comment by ziegm** [comment]
it is a patternCodeableConcept and allows more than one coding. it means at least the fixed one should be provided, but others are allowed. the examples has for example additional loinc codes. with this patternCodeableConcept are no slices needed.

**Comment by qligier** [comment]
Okay, I missed the "Required Pattern: At least the following" on the type. Thanks!
