### ISSUE TITLE
MedicationRequest: duplicate attribute medicationReference

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#164]
In MedicationRequest, the attribute medicationReference is coded twice in the medication[x] slice:
![2022-10-26 15 25 08  cdb2e558a4e0](https://user-images.githubusercontent.com/3299399/198037898-2a0319dc-082b-4408-a9a9-0eb3535d1e70.png)

**Comment by qligier** [comment]
Or is it a weirdness of the UI? I've found another place where it's triggered:
![2022-10-26 15 23 35  940dfee13945](https://user-images.githubusercontent.com/3299399/198037636-1215ada5-470f-4c6a-b62a-21b6dfd0af36.png)

**Comment by ziegm** [comment]
@qligier 
This are screenshots form the Snapshot/Key Elements Table.
The data type 'choice [x]' is visualized that way: first the original "value[x]" and then the chosen type is converted to a slice name. Both are visible in the id of the element (e.g. medication[x]:medicationReference). 

(see also discussion on [zulip](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Choice.20Type.20Renaming))

**Comment by qligier** [comment]
Yes, we've seen that with Oliver yesterday. Seems a weirdness of the publisher.

**Comment by ziegm** [comment]
But an inaccuracy in the differential of the [MedicationStatement (Card)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medicationstatement-card.html) could be fixed, thanks to this issue.

@pjolo
Please review the change.

Before: 
![image](https://user-images.githubusercontent.com/32767151/199463186-8bb51d21-8cc1-4935-a0d1-28dc460f16ab.png)

Now: 
![image](https://user-images.githubusercontent.com/32767151/199464609-ea6dab59-0047-4cd3-b651-91db2e12567a.png)

**Comment by pjolo** [comment]
Checked and good for me.
