### ISSUE TITLE
Profile KeyElements Tab is missing

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-emed#166]
Can we add the KeyElements Tab to ch-emd?

Text Summary, Differential Table

IPS: Differential Table, KeyElements Table

**Comment by ziegm** [comment]
That's already happend (automatically): e.g. http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medication.html

**Comment by oliveregger** [comment]
don't know where i was looking at this morning
