### ISSUE TITLE
Missing elements in CHEMEDObservation

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#175]
There are two missing elements in [CHEMEDObservation](http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-observation.html):

1. **medicationRequestChanged** 0..1 Reference(CHEMEDMedicationRequest) to change a medication request;
2. **dispenseDosageChanged**. This one should contain a single base entry dosage and 0..* additional entry dosages, I don't know how to properly encode it. Can we set it as 0..* and splice it (1..1 CHEMEDDosage and 0..* CHEMEDDosageSplit)? Or do we need to create a complex extension?

**Comment by ziegm** [comment]
12.01. PJ/QL/OE/MZ
* MTP: typo
* PRE: adapt, add a new extension
* DIS: drop this use case

**Comment by ziegm** [comment]
@pjolo @qligier 
Please review the changes:
* [Description](http://build.fhir.org/ig/hl7ch/ch-emed/branches/175_obs/pharmaceutical-advice-document.html#modifying-an-existing-medication) with the linked examples
   * MTP - Change Dosage: Obs -> MedStat
   * PRE - Change Medication: Obs -> MedReq
* [Observation profile](http://build.fhir.org/ig/hl7ch/ch-emed/branches/175_obs/StructureDefinition-ch-emed-observation.html) including the added [extension](http://build.fhir.org/ig/hl7ch/ch-emed/branches/175_obs/StructureDefinition-ch-emed-ext-medicationrequest-changed.html)
   * added also a [rule](http://build.fhir.org/ig/hl7ch/ch-emed/branches/175_obs/StructureDefinition-ch-emed-observation.html#constraints), which checks if a new entry is referenced in case of a 'CHANGE'
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/175_obs/changelog.html)

**Comment by pjolo** [comment]
For me, the changes are ok

**Comment by qligier** [comment]
Looks good to me!
