### ISSUE TITLE
Parent document reference in PML entries

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#176]
In PML variants of MedicationStatement, MedicationRequest, MedicationDispense and Observation, I can't find any place to encode the reference to the parent document UUID.
It's needed to locate and retrieve the full document.

**Comment by ziegm** [comment]
@qligier 
We could use/add the existing extensions for these entries:
- MedicationStatement -> http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-treatmentplan
- MedicationRequest -> http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-prescription
- MedicationDispense -> http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-dispense
- Observation -> http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-pharmaceuticaladvice

See (an earlier) example [here](https://raw.githubusercontent.com/ahdis/hci-analyzer/master/input/resources/parameters/PMP3-List.json).
Would this meet your needs?

**Comment by qligier** [comment]
Yes, that would do it. Thanks!

**Comment by ziegm** [comment]
@pjolo @qligier please review the changes:
* [MedicationStatement (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/StructureDefinition-ch-emed-medicationstatement-list.html)
* [MedicationRequest (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/StructureDefinition-ch-emed-medicationrequest-list.html)
* [MedicationDispense (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/StructureDefinition-ch-emed-medicationdispense-list.html)
* [Observation (LIST)](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/StructureDefinition-ch-emed-observation-list.html)
* Example: [2-1-List](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/Bundle-2-1-MedicationList.html)
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/176_parentdocument/changelog.html)

**Comment by pjolo** [comment]
Changes checked and ok

**Comment by qligier** [comment]
Looks good to me, thanks!
