### ISSUE TITLE
Annotation in PML composition

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#177]
There's no annotation section in the PML composition, whereas it's present in the PMLC composition. I think it should be added; I'd like to use it to describe parameters used to generate the medication list document.

**Comment by ziegm** [comment]
@qligier @pjolo 

Please review the changes:
* Added annotation section to list composition (profile): http://build.fhir.org/ig/hl7ch/ch-emed/branches/177_annotation/StructureDefinition-ch-emed-composition-medicationlist.html
* Updated change log: http://build.fhir.org/ig/hl7ch/ch-emed/branches/177_annotation/changelog.html
