### ISSUE TITLE
How to determine the type of a document by its content?

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#178]
Determining the document type by reading it is required and should be an easy operation.

As of now, I don't see how to easily do that. The document (Bundle) does not contain any useful property for that.

In the composition, the `type` and `category` properties are the most suited for this task. The `category` has no value set associated, so it's not helpful.
The `type` property is defined, but hasn't got a unique code per document type (as discussed in #140): we've got 5 LOINC values and 3 SNOMED CT ones.

To facilitate the before-mentioned task, we've four obvious solutions:

1. Use only the LOINC values and introduce a new one to distinguish between PML and PMLC types.
2. Use only the SNOMED CT values, and introduce 3 new values to distinguish between PML and PMLC, and MTP, DIS and PADV types.
3. Use both LOINC and SNOMED CT values, and introduce a new one (in SNOMED CT) to distinguish between PML and PMLC types.
4. Introduce a new value set for the `category` property, with 6 values.

The last solution is obviously not the better one because it's not that easy and smart. Solutions 1 and 4 seems the best to me.

**Comment by ziegm** [comment]
The current idea, based on [discussion on 10.11.2022](https://github.com/hl7ch/ch-emed/issues/140#issuecomment-1310230216) is the following:
Require one fix code in the Composition profiles for each document type:
* LIST: LOINC 56445-0 Medication summary
* CARD: SCT Medication Plan (see [here](https://github.com/hl7ch/ch-emed/issues/140#issuecomment-1322093573))
* PRE: LOINC 57833-6 Prescription for medication
* MTP: LOINC 77603-9 Medication treatment plan.extended
* DIS: LOINC 60593-1 Medication dispensed.extended	
* PADV: LOINC 61356-2 Medication pharmaceutical advice.extended

**Comment by ziegm** [comment]
Telco 12.01.2023 PJ/QL/OE/MZ:
The [proposed solution](https://github.com/hl7ch/ch-emed/issues/178#issuecomment-1369806350) is still fine.
This issue can be closed, it will be fixed with #140.

**Comment by pjolo** [comment]
This issue can be closed, it will be fixed with https://github.com/hl7ch/ch-emed/issues/140.
