### ISSUE TITLE
Wrong author element for MedicationRequest

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#179]
In https://build.fhir.org/ig/hl7ch/ch-emed//different-authors.html, it's said the author of a prescription is given in `MedicationRequest.performer`, which is the _Intended performer of administration_. It should be `MedicationRequest.requester` (_Who/What requested the Request_).

In CHEMEDMedicationRequestList, the types and descriptions need to be adapted as well.

**Comment by ziegm** [comment]
Overview:
* [CH EMED authors - List](http://fhir.ch/ig/ch-emed/different-authors.html#medication-list-document): PRE: MedicationRequest.performer = author medical decision
* [MedicationRequest.performer ](https://hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.performer) = Intended performer of administration - The specified desired performer of the medication treatment (e.g. the performer of the medication administration).
* [MedicationRequest.requester](https://hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.requester) = Who/What requested the Request - The individual, organization, or device that initiated the request and has responsibility for its activation.

Changes:
* Documentation: 
* Profile:
* Examples: 
* Change Log:

**Comment by qligier** [comment]
Looks good to me!

**Comment by pjolo** [comment]
Changes ok for me
