### ISSUE TITLE
Don't allow nested sections

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#182]
The nested section in the annotation section should not be allowed (Composition.section:annotation.section 0..0), like it is done in the [CARD Composition](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationcard.html). 
It isn't done in all other Composition profiles.

**Comment by ziegm** [comment]
@pjolo please review the changes:
* PRE: http://build.fhir.org/ig/hl7ch/ch-emed/branches/182_nestedsections/StructureDefinition-ch-emed-composition-medicationprescription.html
* DIS: http://build.fhir.org/ig/hl7ch/ch-emed/branches/182_nestedsections/StructureDefinition-ch-emed-composition-medicationdispense.html
* PADV: http://build.fhir.org/ig/hl7ch/ch-emed/branches/182_nestedsections/StructureDefinition-ch-emed-composition-pharmaceuticaladvice.html
* MTP: http://build.fhir.org/ig/hl7ch/ch-emed/branches/182_nestedsections/StructureDefinition-ch-emed-composition-medicationtreatmentplan.html
* LIST (diff. branch): http://build.fhir.org/ig/hl7ch/ch-emed/branches/177_annotation/StructureDefinition-ch-emed-composition-medicationlist.html
* Change Log: http://build.fhir.org/ig/hl7ch/ch-emed/branches/182_nestedsections/changelog.html

**Comment by pjolo** [comment]
Changes ok for me
