### ISSUE TITLE
ValueSets - line break (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#187]
ch.fhir.ig.ch-emed#3.0.0 /ValueSet-ihe-pharmaceuticaladvicestatuslist.html (see [Art-Decor](https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.4&effectiveDate=2020-01-06T13:57:19&language=en-US))
ch.fhir.ig.ch-emed#3.0.0 /ValueSet-edqm-pharmaceuticaldoseform.html (see [Art-Decor](https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.3&effectiveDate=2021-06-01T18:03:30&language=en-US))

Better formatting of comments would improve readability

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/line.20break.20in.20string

**Comment by ziegm** [comment]
Proposed changes (CI build):
* [ValueSet-ihe-pharmaceuticaladvicestatuslist.html](http://build.fhir.org/ig/hl7ch/ch-emed/branches/187_linebreak/ValueSet-ihe-pharmaceuticaladvicestatuslist.html): updated line breaks
* [ValueSet-edqm-pharmaceuticaldoseform.html](http://build.fhir.org/ig/hl7ch/ch-emed/branches/187_linebreak/ValueSet-edqm-pharmaceuticaldoseform.html): removed unused LF

**Comment by ziegm** [comment]
The formatting comes from Art-Decor, no consistent pattern on how to adjust the import accordingly.
@pjolo 
Is there a way to adjust that in Art-Decor or do we leave it as it is and close the issue?

**Comment by pjolo** [comment]
@ziegm The Value Sets were updated.

**Comment by ziegm** [comment]
> We can adjust this in ArtDecor. New representation of: [ValueSet-ihe-pharmaceuticaladvicestatuslist.html](http://build.fhir.org/ig/hl7ch/ch-emed/branches/187_linebreak/ValueSet-ihe-pharmaceuticaladvicestatuslist.html):
> 
> ![image](https://user-images.githubusercontent.com/87263053/214331910-188fa6ee-0bf3-4f77-821d-ef64dca8eb0b.png)
> 
> I will remove the LF tomorrow from [ValueSet-edqm-pharmaceuticaldoseform.html](http://build.fhir.org/ig/hl7ch/ch-emed/branches/187_linebreak/ValueSet-edqm-pharmaceuticaldoseform.html):

The line break before Usage does not work in the input, e.g.: `Change of planning.Usage in case when this...` 
@pjolo I don't know the possibilities in Art-Decor, but could you insert the same linebreak as after `Item:`?

**Comment by pjolo** [comment]
@ziegm I have tried again to insert the line breaks. Can you look again? Unfortunately I can't do any more formatting via Art-Decor.

**Comment by ziegm** [comment]
> @ziegm I have tried again to insert the line breaks. Can you look again? Unfortunately I can't do any more formatting via Art-Decor.

@pjolo Unfortunately, it did not work. I would therefore suggest that issue be closed without further adjustments.

**Comment by pjolo** [comment]
Good for me
