### ISSUE TITLE
Home - Typo (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#191]
ch.fhir.ig.ch-emed#3.0.0 /

The CH EMED implementation guide describes the FHIR representation of the defined documents for the exchange of medication information in the context of the EPR (electronid patient record) in Switzerland. This implementation guide is dependent on CH Core and CH EPR Term, which describe the Swiss specific context, especially related to the Swiss EPR

-> remove defined, electronic instead of electronid

Oliver Egger, ahdis

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* fixed typos -> [Home](http://build.fhir.org/ig/hl7ch/ch-emed/branches/191_typo/index.html)
* [change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/191_typo/changelog.html)

**Comment by pjolo** [comment]
For me, the changes are ok
