### ISSUE TITLE
Relax cardinality for display values (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#194]
We have applied patternCodeableConcepts in some profiles and defined the display value (fixedValue) in addition to the CodeSystem and the code. This causes warnings during validation with examples that include these display values, because they are not the official values as required by http://tx.fhir.org/r4. 
When building the IG these warnings can be suppressed.
But if examples are validated against the profile with the validator, the warnings appear. If you change the display values in the examples to the official ones, there are warnings that they do not match the profile.

The proposal is to remove the display values from patternCodeableConcepts 
* Composition.type (patternCodeableConcept -> fixedValue)
* Composition.section.code (patternCodeableConcept -> fixedValue)

and relax the minimum cardinality 
* Dosage.route.coding.display (min = 1)
* Medication.code.coding.display (min = 1)
* Medication.form.coding.display (min = 1)

**Comment by ziegm** [comment]
ONGOING docu/work
Please review the changes:
* Remove display value from patternCodeableConcept ([Composition]().type/section.code)
* Set minimum cardinality back to 0 for these display values:
   * [Dosage]().route
   * [Medication]().code/form
* Updated values in examples
   * Composition.type (SCT defined in [CH EPR Term](http://fhir.ch/ig/ch-epr-term/2.0.8/ValueSet-DocumentEntry.typeCode.html))
      * LOINC 77603: Medication treatment plan.extended -> Medication treatment plan.extended Document
      * LOINC 60593-1: Medication dispensed.extended -> Medication dispensed.extended Document
      * LOINC 61356-2: Medication pharmaceutical advice.extended -> Medication pharmaceutical advice.extended Document
      * LOINC 56445-0: Medication summary -> Medication summary Document
   * Composition.confidentiality.extension:confidentialityCode = SCT 17621005: Normally accessible -> Normal (qualifier value) (see also [CH EPR Term](http://fhir.ch/ig/ch-epr-term/2.0.8/ValueSet-DocumentEntry.confidentialityCode.html))
   * Composition.section.code
      * LOINC 55108-5: Clinical presentation -> Clinical presentation Document (currently with an issue in the QA -> Issue in CH Core [#200](https://github.com/hl7ch/ch-core/issues/200)
      * LOINC 48767-8: Annotation comment -> Annotation comment [Interpretation] Narrative
      * LOINC 77604-7: Medication treatment plan.brief -> Medication treatment plan.brief Document

**Comment by pjolo** [comment]
OK for me

**Comment by qligier** [comment]
Looks good to me!
