### ISSUE TITLE
Introduce slicing of Composition.author

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#195]
May we should add a slicing on the element Composition.author to allow the additional representation of a Device, see discussion [here](https://github.com/ahdis/ch-emed-pmp/issues/31#issuecomment-1382041831).

Overview documents:
* MTP/PRE/DIS/PADV
   * Composition.author 1..*
      * Composition.author:person 1..* -> PratitionerRole, Patient, RelatedPerson
      * **Composition.author:device** 0..* -> Device (new)
* LIST
   * Composition.author 1..* -> Device
* CARD
   * Composition.author 1..* -> PractitionerRole, Device, Patient, RelatedPerson

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* Composition profiles:
   * [MTP](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/StructureDefinition-ch-emed-composition-medicationtreatmentplan.html)
   * [PRE](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/StructureDefinition-ch-emed-composition-medicationprescription.html)
   * [DIS](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/StructureDefinition-ch-emed-composition-medicationdispense.html)
   * [PADV](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/StructureDefinition-ch-emed-composition-pharmaceuticaladvice.html)
* [Example](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/Composition-2-5-MedicationTreatmentPlan.html) with Device as additional author
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/195_author-slice/changelog.html)

**Comment by pjolo** [comment]
For me, the changes are ok
