### ISSUE TITLE
No restriction of maximum cardinality of contained resources (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#196]
Remove max card = 1 from following elements:
* MedicationDispense.contained
* MedicationRequest.contained
* MedicationStatement.contained

Besides the medication, other resources may be contained.

Adding [aggregation](https://build.fhir.org/elementdefinition-definitions.html#ElementDefinition.type.aggregation) = contained to element medicationReference.

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* Profiles
   * [MedicationDispense](http://build.fhir.org/ig/hl7ch/ch-emed/branches/196_contained/StructureDefinition-ch-emed-medicationdispense.html)
   * [MedicationRequest](http://build.fhir.org/ig/hl7ch/ch-emed/branches/196_contained/StructureDefinition-ch-emed-medicationrequest.html)
   * [MedicationStatement](http://build.fhir.org/ig/hl7ch/ch-emed/branches/196_contained/StructureDefinition-ch-emed-medicationstatement.html)
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/196_contained/changelog.html)

**Comment by pjolo** [comment]
The adaptations are ok
