### ISSUE TITLE
Composition.type: update required patternCodeableConcept (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#206]
At the moment is the pattern fixed to the SNOMED CT code and not the LOINC code. It isn't possible to distinguish between all documents that way, because they have the same SCT code (e.g. MTP and DIS).

Proposal: change to the LOINC codes (according this approved [proposal](https://github.com/hl7ch/ch-emed/issues/178#issuecomment-1369806350), except for CARD (see [here](https://github.com/hl7ch/ch-emed/issues/140#issuecomment-1322093573)).

**Comment by ziegm** [comment]
09.02.2023 PJ/OE/MZ:
Okay that way

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* Composition profiles: [MTP](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/StructureDefinition-ch-emed-composition-medicationtreatmentplan.html), [DIS](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/StructureDefinition-ch-emed-composition-medicationdispense.html), [PRE](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/StructureDefinition-ch-emed-composition-medicationprescription.html), [PADV](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/StructureDefinition-ch-emed-composition-pharmaceuticaladvice.html), [LIST](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/StructureDefinition-ch-emed-composition-medicationlist.html)
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/206_composition-type/changelog.html)

**Comment by pjolo** [comment]
OK for me.
