### ISSUE TITLE
CARD: MedicationStatement.informationSource (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#209]
Possible references should be: PractitionerRole, Patient, RelatedPerson
https://build.fhir.org/ig/hl7ch/ch-emed//StructureDefinition-ch-emed-medicationstatement-card.html

Checked with @qligier and @pjolo

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* [Profile MedicationStatement CARD](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/StructureDefinition-ch-emed-medicationstatement-card.html)
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

**Comment by pjolo** [comment]
OK for me.
