### ISSUE TITLE
Mandatory custodian in Compositions

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#211]
In CH-EMED, `Composition.custodian` is required, it should be optional (as it is in CH-Core).
Linked to #150.

In MTP and PADV composition particularly, patients and relatives have no good organization to put here.
HCPs already have an organization in PractitionerRole, the difference between the two organizations is unclear.

**Comment by ziegm** [comment]
@pjolo @qligier 
Please review the changes:
* removed custodian from profiles/examples: https://github.com/hl7ch/ch-emed/pull/213/files
* [change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue211_custodian/changelog.html)

**Comment by qligier** [comment]
Looks good to me, thanks!

**Comment by pjolo** [comment]
For me also good
