### ISSUE TITLE
Dosages: optionality of dose/rate and frequency

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#214]
I think we have a few points to fix or clarify regarding the usage of dose/rate and frequency in the main and additional dosages.

Split dosing:
I am failing to find a use case where one would want to not set the dose/rate or frequency in an additional dosage. If you don't have one or the other, then you have narrative instructions in the main dosage, and having an additional dosage makes little or no sense.
So both should be required in additional dosages. They should also be required in the main dosage if there are additional dosages.

Normal dosing:
We may have only one of the dose/rate and frequency (as shown in https://github.com/ahdis/ch-emed-pmp/issues/48). There is no strong reason to forbid it, except for the fact that it would be forbidden in split dosages (you either go structured or narrative on these). Allowing it would permit providing more information in structured form.

**Comment by ziegm** [comment]
23.03.2023: PJ/QL/MZ:
* Split dosage: set all min-card to 1
* Normal dosage: if we have a sequence then we have to have timing and doseAndRate (contraint)

**Comment by ziegm** [comment]
Changes: ONGOING
* [CH EMED Dosage Split (MedicationStatement / MedicationDispense)](): set min card to 1

**Comment by pjolo** [comment]
Good from my side

**Comment by qligier** [comment]
Looks good to me, thanks!
