### ISSUE TITLE
Dosages: clarify use of text and patientInstruction

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#215]
We should clarify the use of `text` and `patientInstruction`, as discussed in the last telco, and in light of #214. `additionalInstruction` could also be improved at the same time.

My proposition would be the following:

1. `text` may (shall?) contain the narrative representation of what is provided in structured form;
2. `patientInstruction` shall contain additional information that is not provided in structured form;
3. "Strong" implementations should use structured data and `patientInstruction` to present the information, and may optionally display the `text` for safety reasons.
4. "Weak" implementations should display the `text` and `patientInstruction` fields.

~~On `additionalInstruction`: I suggest making `.text` required inside `additionalInstruction`. Weak implementations could add all descriptions to the displayed narrative, strong implementations could either try to understand the coding or fallback to the description too. The content of `additionalInstruction.text` should not be duplicated to `text` or `patientInstruction`.~~

What do you think about this?

**Comment by oliveregger** [comment]
Telco: clarify 15.3 additionalInstruction would stay optional

**Comment by ziegm** [comment]
23.03.2023: PJ/QL/MZ
1. all structured: patientInstruction + all other elements (timing etc.)
2. complex dosage: only patientInstruction 
3. some structured elements + patientInstruction + some unstructured information (complex dosage) 
 a. all elements structured + text (containig ALL structured information, inc.. patientInstruction): duplicated information
 b. some structured element + patientInstruction (complex dosage) + text (structured elements, patientInstruction)

=> definition text: SHALL include all information from structured elements, incl. patientInstruction
when is text used? 

Procedere: make a proposal for the different types and lets have a look again. try without text

**Comment by qligier** [comment]
Seems good to me, thanks!

**Comment by ziegm** [comment]
06.04.2023 PJ/QL/OE/MZ:
everyone agrees on the changes
