### ISSUE TITLE
Examples conformance to CH-EMED-EPR

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#219]
About [1-1 Medication Treatment Plan document](http://build.fhir.org/ig/hl7ch/ch-emed/Bundle-1-1-MedicationTreatmentPlan.html):

- [ ] `MedicationStatement.dosage[baseEntry].route.text` is required but missing
- [ ] `Composition.informationRecipient`: it should be a CH Core Patient EPR
    * Remove the informationRecipient?
    * Use the same patient as informationRecipient and subject (Patient/MonikaWegmueller)?
    * Change the Reference type in CH-EMED-EPR or CH-EMED?
- [ ] `Medication.form.text` is required but missing

**Comment by ziegm** [comment]
@qligier    
Could you please review the changes and double check that it is now conform to CH-EMED-EPR?

**Comment by ziegm** [comment]
So, we can merge?

**Comment by qligier** [comment]
Yep!
