### ISSUE TITLE
Set the Swiss Extension of SNOMED CT as version (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#224]
ValueSets: see https://github.com/hl7ch/ch-epr-term/issues/18
- http://fhir.ch/ig/ch-emed/ValueSet/ActivePharmaceuticalIngredient
- http://fhir.ch/ig/ch-emed/ValueSet/UnitCode

Instances: 
``` json
          "coding" : [
            {
              "system" : "http://snomed.info/sct",
              "version" : "http://snomed.info/sct/2011000195101",
              "code" : "761931002",
              "display" : "Medication treatment plan report (record artifact)"
            }
          ]
```

**Comment by ziegm** [comment]
@pjolo 
Please review the changes [ci build](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue224_sct-ch-ext/index.html):
* Added SCT Swiss Extension as version to the SCT system (instances)
* update change log

**Comment by pjolo** [comment]
The adjustments are good
