### ISSUE TITLE
Conformance of examples with CH EMED EPR

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#226]
### Bundle-1-2-MedicationDispense

- Missing required MedicationDispense.whenHandedOver.
- MedicationDispense.quantity missing required code, unit, system.

### Bundle-2-4-MedicationDispense

Same changes.

### Bundle-PharmaceuticalAdvice-ChangeDosage

- The changed MedicationStatement shall have the same identifier as the entry it replaces (`urn:uuid:c9f758a1-296c-4710-84d4-e181db8c7478`).

When those changes are made, the PMP accepts the documents.

**Comment by ziegm** [comment]
MedicationDispense.whenHandedOver
- IPAG MDS: Datum, Zeit der Abgabe / Anwendung
   - empfohlen
   - IHE OPTIONAL	
   - Falls relevant und vom Erstellungsdatum des Dokuments abweicht
- That would not speak for making it required

MedicationDispense.quantity
- Add the CH EMED data type quantity (http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-quantity.html) would require the code, unit, system
- would bring consistency, but implementers need to make an additional adjustment

PADV - changed MedicationStatement
- Agree
- In the profile we could add a note in the description (short)

**Comment by qligier** [comment]
MedicationDispense.whenHandedOver: it's required according to the specs.

MedicationDispense.quantity: [FHIR says](http://hl7.org/fhir/R4/medicationdispense-definitions.html#MedicationDispense.quantity): "The amount of medication that has been dispensed. Includes unit of measure." Not sure what it implies exactly, but requiring the units is a good idea.

PADV - changed MedicationStatement: In the description and in the CH EMED EPR workflows, it would be good. I've added the following assertions to check it in the profile: https://github.com/CARA-ch/ch-emed-epr/blob/10969ecbe2ca335f13aaa1c1cb186e54f9516077/input/fsh/structuredefinition/observation.fsh#L97-L105

**Comment by ziegm** [comment]
@pjolo @qligier 
Please review the changes:
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue226/changelog.html): Added values to examples (MedicationDispense.whenHandedOver, MedicationDispense.quantity.code/unit/system) and corrected identifier of the changed MedicationStatement (added a note to the Observation profile)
* see [changed files](https://github.com/hl7ch/ch-emed/pull/227/files) and [ci build](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue226/index.html)

@qligier 
Could you also retest with the PMP?

**Comment by pjolo** [comment]
For me the changes are good.

**Comment by qligier** [comment]
The three documents are now CH EMED EPR valid :)
