### ISSUE TITLE
MedicationDispense: Snomed CT Code 294121000195110 not valid

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-emed#228]
tx.fhir.org loaded with the swiss extension gives an error during IG publication

> Unable to find code 294121000195110 in http://snomed.info/sct (version http://snomed.info/sct/900000000000207008/version/20230131); Unknown Code '294121000195110' in the system 'http://snomed.info/sct'; The provided code http://snomed.info/sct#294121000195110 is not in the value set 'http://hl7.org/fhir/ValueSet/@all' (from Tx-Server) for 'http://snomed.info/sct#294121000195110'

If we look up the code it looks like a valid SNOMED CT code, however on the right side we see that it has a different SNOMED CT identifier:

![Screenshot_20230629-105034](https://github.com/hl7ch/ch-emed/assets/2414516/c2fc36f2-5072-41e9-a07a-c0218fffbeb4)

Might that be the problem causing the issue?

**Comment by oliveregger** [comment]
https://browser.ihtsdotools.org/?perspective=full&conceptId1=82291000195104&edition=MAIN/SNOMEDCT-CH/2023-06-07&release=&languages=en,fr,de,it&latestRedirect=false

**Comment by oliveregger** [comment]
sctid: 82291000195104

**Comment by oliveregger** [comment]
related to https://github.com/hl7ch/ch-emed/issues/140

**Comment by oliveregger** [comment]
@PeroGrgic might you investigate why we have a 
sctid: 82291000195104 for Medication dispense document (record artifact)?

**Comment by PeroGrgic** [comment]
@oliveregger 
The 82291000195104 is the ID of the concept and 294121000195110 is the ID of the Fully Specified Term. I must have sent Patrick the wrong ID in https://github.com/hl7ch/ch-emed/issues/140

**Comment by ziegm** [comment]
@pjolo could you please review the [changes](https://github.com/hl7ch/ch-emed/pull/229/files)

**Comment by pjolo** [comment]
The change is good
