### ISSUE TITLE
ch-ext-epr-time is still used

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#230]
Despite #150, ch-ext-epr-time is still used in the specification.

We should either remove it completely, or add it everywhere.

Related discussion: https://github.com/CARA-ch/ch-emed-epr/issues/25

**Comment by ziegm** [comment]
I added this issue as feedback in my ballot response

**Comment by ziegm** [comment]
see discussion from [here](https://github.com/CARA-ch/ch-emed-epr/issues/25#issuecomment-1711223536) on 

@pjolo do you agree to close the issue without any work on CH EMED?

**Comment by pjolo** [comment]
I agree that no changes should be made to CH EMED and that the issue can be closed.
