### ISSUE TITLE
SCT codes without version (if not Swiss extension) (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#233]
ch.fhir.ig.ch-emed#4.0.0-ballot /Bundle-2-7-MedicationCard.json.html

Only add the version (Swiss extension) to SCT codings if the code itself comes from the Swiss extension.
If only the display value comes from the Swiss extension but the code is from the international edition, do the coding without version.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
see also https://chat.fhir.org/#narrow/stream/179202-terminology/topic/coding.2Eversion.20for.20SCT.20extension

**Comment by ziegm** [comment]
there is an error in the generated example, see https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/different.20results.3F
(check, if it is correct when we close the issue)

**Comment by ziegm** [comment]
Changes (still in progress):
* [remove coding.version](https://github.com/hl7ch/ch-emed/pull/235/files) for all SCT codings, except Composition.type DIS ([profile](), [examples]()), where the code is from the Swiss extension
* fix that we do not have the sct version in the loinc coding ([example DIS]())
* [changelog]()

**Comment by ziegm** [comment]
@oliveregger 
could you please remove the sct version (swiss extension) for the valueset import from art-decor?
* ActivePharmaceuticalIngredient
* UnitCode

**Comment by oliveregger** [comment]
is added https://github.com/hl7ch/ch-emed/pull/235/commits/4f0a61c0beaad20180a09263132b2853b32649ca

**Comment by ziegm** [comment]
@pjolo please review the changes:
* [remove coding.version](https://github.com/hl7ch/ch-emed/pull/235/files) for all SCT codings (profiles, examples, valuesets ([UnitCode](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue233_sct-ch/ValueSet-UnitCode.html), [ActivePharmaceuticalIngredient](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue233_sct-ch/ValueSet-ActivePharmaceuticalIngredient.html))), where the code is from the international edition (diplays may from the swiss extension)
   * except [Composition.type DIS](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue233_sct-ch/StructureDefinition-ch-emed-composition-medicationdispense.html), where the code is from the Swiss extension
* fix that we do not have the sct version in the loinc coding ([example DIS](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue233_sct-ch/Composition-1-2-Composition.json.html))
* [changelog](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue233_sct-ch/changelog.html)

**Comment by pjolo** [comment]
For me the changes are good.
