### ISSUE TITLE
Datatype Profiles (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#238]
ch.fhir.ig.ch-emed#4.0.0-ballot /profiles.html

Adding data type profiles to the profile tab would make the navigation easier

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo please review the changes:
* [profiles](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue238_datatypeprofiles/profiles.html#data-type-profiles)
* [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue238_datatypeprofiles/changelog.html)

**Comment by pjolo** [comment]
good for me
