### ISSUE TITLE
Authorship fields

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#241]
As part of the changes triggered by https://github.com/hl7ch/ch-emed/issues/234 the Observation.performer will have to be filled, to comply with a best practice attached to it: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Get.20Warning.20About.20Performer.20Element.20in.20Observation.20Profile
Also from this conversation on the FHIR chat, I would highlight the following:

> Is this a situation where no one who receives the Observation (whether the immediate intended recipient, or some eventual downstream recipient) will need to know the recipient and there's no expectation it'll be inferred from something else? If so, fine to omit. If there's an expectation that the performer is inferred from contextual knowledge, then the performer should be populated - because FHIR doesn't support/encourage inference from context. Every resource should always stand alone.

This might conflict a bit with how we are dealing with the authorship and the resources. At the time of writing this the guidance for provided stable documents is to fetch the authorship from the composition, which is expected to provide a composition author (document authorship and, unless otherwise provided, presumed medical authorship) and, if different from the composition author, a section author (explicit medical authorship) while the corresponding field on the resource (e.g. `Observation.performer`) is not necessarily filled or checked (with the exception of `Observation.performer` from now on).
This presents the following conundrum:

- The resources do not (necessarily) contain the medical author. Except for observations now.
- When generating a PML document, the relevant resources have to be provided and in order to provide medical authorship, the system will have to alter the stocked resources to include the medical authorship in the resource. This means the stocked resources are in fact _not stand-alone_.
- Regarding the generation of the PMLC, it is more arguable whether this presents a problem.
  - If an aggregator does the aggregation upon ITI-41 of a stable document (which is the case of CARA's PMP), then the aggregated information is already stocked from the submission and it does not matter that the resources themselves alone do not contain the relevant information needed to generate the PMLC.
  - If an aggregator does the aggregation operation on-demand, when generating the content of the PMLC document, then the resources themselves are not enough to generate the PMLC and the content of the document's composition will be needed in order to fill the authorship information.

On top of this, this is somehow, in my opinion, related to the management of the authorship timestamps. As I have already commented, in a context in which medical authorship timestamp might differ from document authorship, at the moment the only option is the following:

- Using the document/composition timestamp as document authorship timestamp of the provided stable documents' resources.
- On-demand documents:
  - There is no option for specifying the document authorship timestamp for PML attached resources. This does not seem to be relevant in our context, though.
  - For PMLC generation, the medication statements are to be considered generated, not the original, and hence the document authorship can be considered to be the PMLC document/composition and the same for its timestamp. However, we do have `authorDocument`: we are including here in a generated resource a document authorship information from the original submission, but not the timestamp of this. Again, not really relevant but I wonder how coherent this is.
- Using the resource timestamp for medical authorship timestamp.
  - This is absolutely needed for PML and PMLC generation, since there is no other way to specify it.

Questions:
- If it is best practice to always add the medical author of the observation (within the resource), shouldn't we do the same for all other medical authorship fields?
- Is it useful to use the section's author field as medical authorship field in the guidance? Using the relevant resources' fields (along with the timestamp fields) for the medical authorship would align where that information can be found for both stable and on-demand documents and make the resources _stand-alone_.
  - Furthermore, this would allow PML generation to avoid modifying a resource (for which it is supposed to only return it, keeping its identifier).
  - This would imply making the following choice:
    - Either medical authorship fields become mandatory for all provided stable documents.
    - Or the aggregator software fills this information (if medical author is not specified, fill these fields with the document/composition authorship information) either at provide time (so the resources are already stocked with all their relevant information, being from then on _stand-alone_) or at on-demand document generation time.
  - section.author would have to be reviewed: either it is assumed to contain nothing or the same kind of information as composition.author or if it should still contain medical authorship, it should then contain the same information as the relevant medical authorship field in the resource.

**Comment by dvribeira** [comment]
Hi, the spreadsheet is really great. I am not sure I understand exactly the difference of MIN-Card. column, which I guess it is minimum cardinality, for the entries' medical decision author for CARD (0) and LIST (1).
![imagem](https://github.com/hl7ch/ch-emed/assets/133101442/d4be5d6f-a958-47ce-ba05-ebecb6e1b993)

**Comment by ziegm** [comment]
I updated the spreadsheet, you are right, thanks. 
Would that summarize your request then?

**Comment by dvribeira** [comment]
Yes, that's perfect. Thanks a lot!

**Comment by ziegm** [comment]
19.10.2023 PJ/OE/MZ
We would present the proposal during the next CARA spec call and asked there if it would be an acceptable change.

**Comment by dvribeira** [comment]
Hi there, concerning the timestamps I didn't notice before but I would have the following remarks about the proposal in the spreadsheet:

- For the Observation, I would have expected to use the `issued` field instead of `effectiveDateTime`. In fact `effectiveDateTime` is also present in the medication statements but not used.
- Also in case of PADV documents, I guess it would be useful to specify that the respective fields in the CHEMEDMedicationRequestChanged and CHEMEDMedicationStatementChanged resources should also be filled with the medical authorship information for PADV CHANGE observations.

**Comment by ziegm** [comment]
> 19.10.2023 PJ/OE/MZ We would present the proposal during the next CARA spec call and asked there if it would be an acceptable change.

Feedback 01.11.2023 Cheri Gey: _"We are fine with the proposed change"_

**Comment by ziegm** [comment]
> Hi there, concerning the proposal I didn't notice before but I would have the following remarks about the proposal in the spreadsheet:
> 
> * For the Observation, I would have expected to use the `issued` field instead of `effectiveDateTime`. In fact `effectiveDateTime` is also present in the medication statements but not used for this, since its description is `The date/time or interval when the medication is/was/will be taken`.
> * Also in case of PADV documents, I guess it would be useful to specify that the respective fields in the CHEMEDMedicationRequestChanged and CHEMEDMedicationStatementChanged resources should also be filled with the medical authorship information for PADV CHANGE observations. This is perhaps not relevant for the spreadsheet itself but to be taken into account for updating the guidance.

1. Yes, I agree, please see also MedicationDispense
MedicationStatement.dateAsserted 1..1 (When the statement was asserted?)
MedicationRequest.authoredOn 1..1 (When request was initially authored)
MedicationDispense.whenHandedOver 1..1 -> that is also not the correct field I think @dvribeira do you have a proposal? (I haven't)
Observation.issued 1..1 (Date/Time this version was made available)

2. Those profiles have the updated profiles as parent, so the requirement is also valid there

**Comment by dvribeira** [comment]
Concerning the dispense, for us `whenHandedOver` is fine as date of the authorship, `whenPrepared` might be of certain use internally to dispenser actors but not necessarily of much use outside. For the moment we do not even support `whenPrepared` in CH-EMED-EPR. However, the _medical act_ of interest is when the dispense is effective i.e. `whenHandedOver`. It is not identical but it provides similar value as the time at which a treatment was effectively planned (`dateAsserted`) or when a prescription was done (`authoredOn`): these actual actions and not necessarily the time of documentation (document creation date) and to me it is the same with `whenHandedOver`. 
In any case I don't see any other field that would be suitable instead.

**Comment by pjolo** [comment]
The changes are good thank you very much.
