### ISSUE TITLE
Incoherent names of documents.

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-emed#243]
This is not essentially an issue of this IG, but we have too many different names for the documents, look at this example:
- FHIR: Medication Card Document
- IPAG: eCurrentMedication
- IHE:   Community Medication List (PML)
- type Medication summary Document (LOINC 56445-0)
- type Medication management plan (SNOMED CT 736378000)

Proposal: The IG could use the LOINC Term: Medication summary Document, which is distinct of the other documents.

**Comment by ziegm** [comment]
similar to this earlier issue: https://github.com/hl7ch/ch-emed/issues/139

**Comment by pjolo** [comment]
Yes, depending on the source, other names are used for the documents. As described in the [Factsheet eMedikation](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/D/factsheet-emedikation.pdf), we have chosen the following names:


- Medication Treatment Plan document
- Medication Prescription document
- Pharmaceutical Advice document
- Medication Dispense document
- Medication List document
-Medication Card document

**Comment by ziegm** [comment]
19.10.2023 PJ/OE/MZ:
This was a harmonization effort between IHE, IPAG and eHS and the different names have been fixed, e.g. there is not one Medication Summary document, CARD and LIST are two different kind of documents.

**Comment by ziegm** [comment]
@lpg-tech FYI please see the comments above

**Comment by ziegm** [comment]
@pjolo Please review the https://github.com/hl7ch/ch-emed/pull/247

**Comment by pjolo** [comment]
Good
