### ISSUE TITLE
Missing EDQM MOA (method of application) (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#245]
ch.fhir.ig.ch-emed#4.0.0-ballot /

During the Projecathon 2023 we came across the fact that we cannot seamlessly map the application types in our EHR system, which have been tried and tested for almost 25 years, to EDQM ROA. In particular, we lack a way to code infusion and instillation to differentiate intravenous, something that would be possible with HCI Solutions via EDQM MOA and is provided for in ChMed23A. I would ask to check whether this cannot also be taken into account in the exchange format. Or if not appropriate, the Snomed CT Valuesets would also allow more differentiation, cf. Descendants of SCTID: 284009009 Route of administration value (qualifier value) and Descendants of SCTID 129445006 Administration - action (qualifier value).
 

Daniel Ratschiller, CISTEC AG

**Comment by ziegm** [comment]
@pjolo could you check that with IPAG?

**Comment by ziegm** [comment]
https://standardterms.edqm.eu/ 
"The Standard Terms database contains terms and definitions to describe pharmaceutical dose forms, routes and **methods of administration**, containers, closures, administration devices and units of presentation."

**Comment by drats-cis** [comment]
Dear Michaela

Ok, maybe I can show you what I mean via the following screenshots and attachment:

(Side finding, at HCI there is missing an official ROA-20088000 Perilesional use)

https://standardterms.edqm.eu/browse/get_concepts/ROA (Result of the export see appendix, only 104 lines with 8-digit numbers from 20001000 - 20088000)
![image](https://github.com/hl7ch/ch-emed/assets/80474467/13b36a27-9850-409a-acee-8a0380f3b1dc)

https://standardterms.edqm.eu/browse/get_concepts/MOA (null results, experimentally called!)
![image](https://github.com/hl7ch/ch-emed/assets/80474467/91215df0-e500-4c09-b0a4-84c888bc9da0)

On the other hand, the HCI index:
https://index.hcisolutions.ch/DataDoc/element/PRODUCT/PRD/CPT/EDQMROAS/EDQMROA  
https://index.hcisolutions.ch/datadoc/element/PRODUCT/PRD/CPT/EDQMROAS/EDQMMOA
![image](https://github.com/hl7ch/ch-emed/assets/80474467/46652115-4945-409e-9f98-40f26a52775b)

EDQM-MOA (1-3 digit numbers) according to HCI
https://index.hcisolutions.ch/index/current/get.aspx?schema=CODE&keytype=CDTYP&key=61&xsl=table.xslt
![image](https://github.com/hl7ch/ch-emed/assets/80474467/57d64f31-a15f-4a9c-a9d2-c4708ecd2088)

EDQM-ROA (8-digit numbers) according to HCI
https://index.hcisolutions.ch/index/current/get.aspx?schema=CODE&keytype=CDTYP&key=61&xsl=table.xslt 
![image](https://github.com/hl7ch/ch-emed/assets/80474467/bd7dcee4-a4a8-4936-a371-eeb6eec2bf88)


[EDQM_ROA_official_HCI.xlsx](https://github.com/hl7ch/ch-emed/files/13320781/EDQM_ROA_official_HCI.xlsx)

We will actually have the difficulty that with ROA alone (as currently in HL7 FHIR CH-EMED), for example, it is actually not possible to distinguish well between IV as an infusion and IV as an injection. in in CHMED23A ROA and MOA are adressed. But where are they officially available in the EU?

LG Daniel

**Comment by ziegm** [comment]
@pjolo That's great! Then we'll continue as discussed (16.11.2023 PJ/OE/DR/MZ)
- Integration of this feature request in the next release (v5.0.0-ballot)
   - Mapping in Dosage.method
   - Development of a ValueSet

@drats-cis do you agree?

**Comment by oliveregger** [comment]
there are also so MOA defined here: https://build.fhir.org/ig/hl7-eu/unicom-ig/ValueSet-administration-method.html

**Comment by drats-cis** [comment]
Hello everyone
This is also good news for me.
However, I have asked the EDQM helpdesk whether it is a bug that the MOA codes can no longer be found there and would then post the answer here.
https://helpdesk.edqm.eu/servicedesk/customer/portal/1/HELP-30785
LG Daniel

**Comment by drats-cis** [comment]
See answer from Christopher JARVIS07/Dec/23 11:08 AM

I think that the confusion has arisen from the fact that we have '**Routes and methods of administration**' (ROA) as a list of Standard Terms, and '**Administration method' (AME)** as a separate list, as it is one of the characteristics for pharmaceutical dose forms. You can find all of these characteristics in the [Internal controlled vocabularies for pharmaceutical dose form](https://www.edqm.eu/sites/default/files/standard_terms_internal_vocabularies_for_pharmaceutical_dose_forms.pdf) document (accessible under the 'Guidance and change requests' section on the homepage of the Standard Terms database after logging in).

You can also see the list of AME terms directly in the database here: [https://standardterms.edqm.eu/browse/get_concepts/AME](https://standardterms.edqm.eu/browse/get_concepts/AME), however they are not full Standard Terms, so you won't find all of the same information (translations, etc.) as you would for the list of ROA.

This cleared up my concern that something was wrong with the MOAs, it's just not as easy to find as the ROAs.

**Comment by ziegm** [comment]
> Hello everyone This is also good news for me. However, I have asked the EDQM helpdesk whether it is a bug that the MOA codes can no longer be found there and would then post the answer here. https://helpdesk.edqm.eu/servicedesk/customer/portal/1/HELP-30785 LG Daniel

Is the answer from Christopher underneath the answer from the helpdesk? I cannot open the helpdesk answer without login, that's why I'm asking.

**Comment by drats-cis** [comment]
Hello, yes, I just attached the full content of the answer here:
[Disappeared MOA_ - HelpDesk - Service Desk.pdf](https://github.com/hl7ch/ch-emed/files/13952723/Disappeared.MOA_.-.HelpDesk.-.Service.Desk.pdf)

**Comment by pjolo** [comment]
I have received the list from HCI with the translations in French and Italian
[MOA_EDQM (002).xlsx](https://github.com/hl7ch/ch-emed/files/14165941/MOA_EDQM.002.xlsx)

**Comment by ziegm** [comment]
08.02.2024: PJ/OE/MZ/AB
Next steps:
include the codes to CS EDQM, create VS MOA, add VS binding in profile, add example
(term directly in CH Term, not Art-Decor)

**Comment by ziegm** [comment]
@pjolo 
1. Can you support me with the missing translations ("null")?
2. Do we have an OID for this ValueSet (like we have one for ROA)? Or do we need an OID?
see [ci build CH Term]() (branch)

**Comment by pjolo** [comment]
@ziegm I added all translations to the table below.

Code | Display | Deutsch (Schweiz) (German (Switzerland), de) | French (Switzerland) (fr) | Italian (Switzerland) (it) | rm
-------- | -------- | -------- | -------- | -------- | --------
0004 | Administration | Administration | Administration | Somministrazione | **Administraziun**
0005 | Application | Applikation | Application | Applicazione | **Applicaziun**
0006 | Bathing | Baden | Baigner | Bagnare | **Bogn**
0007 | Chewing | Kauen | Mâcher | Masticare | **Tschavera**
0008 | Gargling | Gurgeln | Se gargariser | Gargarizzare | **Sgarguglias**
0009 | Infusion | Infusion | Perfusion | Infusione | **Infusiun**
0010 | Inhalation | Inhalation | Inhalation | Inalazione | **Inhalaziun**
0011 | Injection | Injektion | Injection | Iniezione | **Injecziun**
0012 | Insertion | Insertion | Insertion | Inserzione | **Inserziun**
0013 | Instillation | Instillation | Instillation | Instillazione | **Installaziun**
0014 | Orodispersion | **Orodispersion** | **Orodispersion** | **Orodispersione** | **Dispersiun d'odi**  
0015 | Rinsing/washing | Spülen/Waschen | Rincer/Laver | Sciacquare/Lavare | **Derschentar/Lavar**
0017 | Spraying | Sprühen | Pulvériser | Spray | **Squitta**
0018 | Sucking | Lutschen | Sucer | Succhiare | **Luschezza**
0019 | Swallowing | Schlucken | Avaler | Per deglutizione | **Tragutter**
0020 | Not specified | Keine Angaben | Non spécifié | Non specificato | **Naginas indicaziuns**
0111 | Burning | Brennen | Brûler | Bruciare | **Arder**
0112 | Dialysis | Dialyse | Dialyse | Dialisi | **Dialisa**
0113 | Implantation | Implantation | Implantation | Impianto | **Implantaziun**

Regarding the OID, I think it is good if the value set runs under the node of HL7 Switzerland (urn:oid:2.16.756.5.30.1.1.....).
![image](https://github.com/hl7ch/ch-emed/assets/87263053/39109b6f-27f1-456d-a726-cfeb56ae9652)

**Comment by ziegm** [comment]
@oliveregger @pjolo 
- Do we need an OID?
- It isn't a Art-Decor ValueSet.

**Comment by ziegm** [comment]
22.02.2024 PJ, OE, MZ, AB:
- OID is not necessary for this VS

**Comment by pjolo** [comment]
From my side the changes are good.
