### ISSUE TITLE
Medication Dispense document (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#246]
ch.fhir.ig.ch-emed#4.0.0-ci-build /medication-dispense-document.html

Typo: Beispiel 1-1, statt 1-2 (wie verlinkt)

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo Please review the https://github.com/hl7ch/ch-emed/pull/247

**Comment by pjolo** [comment]
Change is fine for me
