### ISSUE TITLE
UnitCode problems when used as unit of dosage

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#250]
**Our problem:**

There are two semantically different units to be used: units of presentation (what comes in the packaging/article) and units of administration (units suitable to express drug intake/administration). At present, CH EMED uses, besides the UCUM codes, only the SNOMED codes for unit of presentation for both cases (e.g. `Medication.amount` through `CHEMEDRatioWithEmedUnits` fields numerator and denominator being `CHEMEDQuantityWithEmedUnits` which have the `code` bound to `UnitCode`). Now, for instance, in the case of a treatment with an inhaler, the unit of presentation would be, as it is the case now, code [732997007](http://snomed.info/id/732997007) i.e. `Inhaler`. Now if the planned dosage is to be twice inhalations per day, we cannot use the same unit, since that would mean that the intake is 2 inhalers per day and not two inhalations. For this, SNOMED has codes for unit of drug administration: https://browser.ihtsdotools.org/?perspective=full&conceptId1=408103002 which would allow us to use for this example the code `422237004` for `Inhalation` (https://browser.ihtsdotools.org/?perspective=full&conceptId1=422237004).

**Proposal:**

- Keep the medication resource as is, using `CHEMEDRatioWithEmedUnits` for the `amount` field.
- Keep `CHEMEDRatioWithEmedUnits` using `CHEMEDQuantityWithEmedUnits` for both `numerator` and `denominator` fields but rename it to something like `CHEMEDRatioWithEmedPresentationUnits`.
- Rename `UnitCode` to `PresentationUnitCode`.
- Rename `CHEMEDQuantityWithEmedUnits` to `CHEMEDQuantityWithEmedPresentationUnits`.
- Add new value set `AdministrationUnitCode` or `DoseUnitCode` with the same UCUM codes but using the SNOMED codes from https://browser.ihtsdotools.org/?perspective=full&conceptId1=408102007 instead.
- Add the data type `CHEMEDQuantityWithEmedDoseUnits` with `code` bound to `DoseUnitCode`.
- Rename `CHEMEDRangeWithEmedUnits` to `CHEMEDRangeWithEmedDoseUnits` and change `low` and `high` fields to use `CHEMEDQuantityWithEmedDoseUnits`.
- Replace `CHEMEDQuantityWithEmedUnits` with `CHEMEDQuantityWithEmedDoseUnits` in the dosage data types:
  - `CHEMEDDosage.doseAndRate.doseQuantity`
  - `CHEMEDDosageSplit.doseAndRate.doseQuantity`

I hope this is clear but let me know what you think or if something is not clear or if I can provide anything else to help.

**Comment by ziegm** [comment]
[TODO](https://docs.google.com/spreadsheets/d/17oX8hRPJRFpvCtO9WJKzJsCOfZe60r8yRZlJ4thEfi4/edit?usp=sharing)

**Comment by dvribeira** [comment]
I somehow missed the notification 5 days ago. I will have a look first thing this afternoon. Thanks a lot!

**Comment by dvribeira** [comment]
@ziegm The proposal is well summarized in the excel. Perhaps the example I provided is not the best since one could use either _inhalation_ or indeed _actuation_ to express the dosage. Perhaps it would be more tricky for an _applicator_ for which we would have _application_ in the units of administration for instance for https://compendium.ch/product/1510171-bepanthen-med-creme and a very difficult choice on the current UnitCode.

Thanks!

**Comment by ziegm** [comment]
May you could add the example in the sheet?

**Comment by dvribeira** [comment]
@ziegm I have added two examples that I hope are of use by using the data on the HCI indices.

**Comment by ziegm** [comment]
16.11.2023 PJ/OE/MZ:
Var 1: Proposal from this issue
Var 2: stay with 1 VS and add additional codes
**Next step:** Integrate a proposal for Var 1 in the next release (v5.0.0-ballot) and collect feedback from the implementers

**Comment by dvribeira** [comment]
I know this will not be part of 4.0.0 but in any case **I would ask to put this on hold** for a while. After another meeting for feedback with a pharmacist we have found that it seems the second set of SNOMED codes (the ones for administration) would also be incomplete after all (at least for what it concerns HUG's PRESCO application). I am trying to get a more complete view of each involved implementer's needs on this in the hopes I can finally get a proper view of this. In the meantime I apologize for any possible wasted effort and ask not to proceed with this for now.

Once I manage to gain a better understanding of the other system's needs I will get back to this issue.

Thanks a lot :)

**Comment by ziegm** [comment]
@dvribeira 
As we are already starting to work on the ballot version, I'd like to know where you are standing on this issue, because you asked to put it on hold. Thx!

**Comment by dvribeira** [comment]
@ziegm Sorry for the delay, I have returned from my holidays only today. I managed to get feedback from all the involved implementers only just before the Christmas holidays, so I didn't have time yet to fully address this on our side. However, I can say that:

- It seems we would still be missing some important units in the SNOMED units of administration set.
- If we would have to also complete _units of administration_ then we could live with just completing the current UnitCode value set with what's missing and not separating in two value sets. This should be easier for implementers.

I do not think I will find the time to work on this on what's left of the week, but I hope to work on this next week. Since this work will entail also discussions it might still take a while until I can provide more refined (and more _final_) feedback on this: I wish to firmly establish which units are needed and how to map them for all the actors involved.

In the meantime: how feasible do you think it would be to add values to UnitCode that are not currently in neither of the aforementioned SNOMED sets?

Many thanks!
Daniel

**Comment by ziegm** [comment]
21.03.2024 PJ, DV, QL, MZ, AB
- units are missing: 
   - UCUM: nanomol
   - SCT 413568008 | Application - unit of product usage (qualifier value) (@pjolo check with @PeroGrgic )
- add it to https://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-UnitCode.html

**Comment by pjolo** [comment]
@ziegm 
- Do I have to insert the code nmol (nanomole) in ArtDecor or can this be done directly in CH Term?
- The SNOMED code 413568008 | Application - unit of product usage (qualifier value) can be included. For the translations, it must be checked if there is enough time for the Swiss extension release.

**Comment by ziegm** [comment]
> @ziegm
> 
> * Do I have to insert the code nmol (nanomole) in ArtDecor or can this be done directly in CH Term?
> * The SNOMED code 413568008 | Application - unit of product usage (qualifier value) can be included. For the translations, it must be checked if there is enough time for the Swiss extension release.

@pjolo yes please, include both in art decor

**Comment by pjolo** [comment]
@ziegm I have included both codes

![image](https://github.com/hl7ch/ch-emed/assets/87263053/33d0da21-a6d9-439b-a727-ba0b1afa6bbc)

![image](https://github.com/hl7ch/ch-emed/assets/87263053/7b765f20-0df4-406c-9aa1-3f4dcb554c2e)

**Comment by ziegm** [comment]
@oliveregger could you please update the import of the CH Term VS from Art-Decor?

**Comment by ziegm** [comment]
@dvribeira @pjolo you can review the changes:
* CH Term
   * [VS UnitCode](https://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-UnitCode.html)
   * [Changelog](https://build.fhir.org/ig/hl7ch/ch-epr-term/changelog.html)
* CH EMED
   * [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

**Comment by pjolo** [comment]
From my side the changes are good

**Comment by dvribeira** [comment]
Good for me too. Thanks!
