### ISSUE TITLE
SCT code for {Piece} 'Piece' (UCUM)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#252]
* Based on this issue: https://github.com/hl7ch/ch-emed/issues/234
* see this comment: https://github.com/hl7ch/ch-emed/issues/234#issuecomment-1786845282
  _Für “Stück”/”Piece” habe ich nichts Passendes gefunden. Ich frage nochmals bei SNOMED International nach, warum piece nicht als Unit eingeführt wurde. Falls SNOMED International auch keinen passenden Code hat oder er einfach noch nicht eingeführt wurde, können wir ihn im International Release einreichen oder, falls SNOMED ihn ablehnt, in die Swiss Extension aufnehmen.
Für beide Möglichkeiten sehe ich die Einführung des Codes nicht vor Dezember/Januar._

**Comment by qligier** [comment]
Indeed, if HCI's INDEX uses `piece` as packaging unit, we won't be able to do without.
But their prescription unit is not `piece`, so we may want to forbid the use of `piece` as `quantity` (while still authorizing it as packaging unit) if there is no real world usage.

**Comment by PeroGrgic** [comment]
As mentioned in the previous comment, "piece" is a quantity and not a unit of measurement. We searched in SNOMED CT again for a suitable code for quantities and found the following codes:

- 246205007 |Quantity (attribute)| with synonym "amount"
- 410680006 |Number (attribute)|

The pack size indicates the amount of tablets as a number. The two SNOMED CT codes would therefore be suitable.

**Comment by ziegm** [comment]
22.02.2024 PJ, OE, MZ, AB
246205007 |Quantity (attribute)| with synonym "amount"
@pjolo Update in Art-Decor
@oliveregger Update in CH Term
@ziegm Update CH EMED (example)

**Comment by pjolo** [comment]
@ziegm I have added the code to Art Decor
![image](https://github.com/hl7ch/ch-emed/assets/87263053/073dacee-5d4b-4d63-b66e-f1ab8c4cb1b5)

**Comment by oliveregger** [comment]
@pjolo der code ist in art-decor noch dem UCUM Codesystem zugeordnet, nicht SNOMED CT, kannst Du das umstellen? Oder soll ich es selber umstellen?

**Comment by pjolo** [comment]
@oliveregger : 
Danke für den Hinweis. Ich habe es angepasst:
![image](https://github.com/hl7ch/ch-emed/assets/87263053/503100b7-24ed-4dbe-ab4e-67c394dac533)

**Comment by ziegm** [comment]
ongoing

* CH Term
   * [VS UnitCode](https://build.fhir.org/ig/hl7ch/ch-epr-term/branches/oe_unit_252/ValueSet-UnitCode.html)
   * [Changelog](https://build.fhir.org/ig/hl7ch/ch-epr-term/branches/oe_unit_252/changelog.html)
* CH EMED
   * [Example](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue252/Medication-MedicationWithTwoIngredients.json.html)
   * [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue252/changelog.html)

**Comment by pjolo** [comment]
@ziegm In CH Term, the code is not displayed correctly in the table below and is not defined as a SNOMED CT code. The example is good.

![image](https://github.com/hl7ch/ch-emed/assets/87263053/55f0cb4a-d3ae-41c4-b79c-66ab34a6f604)

**Comment by ziegm** [comment]
@pjolo 
was the wrong branch: https://build.fhir.org/ig/hl7ch/ch-epr-term/branches/master/ValueSet-UnitCode.html
![image](https://github.com/hl7ch/ch-emed/assets/32767151/64956d86-30de-43ae-b22a-d8c4e67e03b0)

**Comment by pjolo** [comment]
The changes are good
