### ISSUE TITLE
EDQM - Standard Terms (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#253]
ch.fhir.ig.ch-emed#4.0.1 /CodeSystem-edqm-standardterms.html

Das CodeSystem definiert das Element content = complete, das stimmt aber nicht, da z.B. 15001000 nicht vorhanden ist.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
PJ/OE/MZ/AB 08.02.2024
- technical correction would be okay
- waiting on feedback from @PeroGrgic if we add all EDQM codes to the CS

**Comment by ziegm** [comment]
22.02.2024 PJ, OE, MZ, AB
- change to "fragment"

**Comment by ziegm** [comment]
fixed with https://github.com/hl7ch/ch-epr-term/pull/28
