### ISSUE TITLE
Terminology to CH EPR Term (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#256]
Move all terminology to CH EPR Term

@ziegm CH EMED term
@oliveregger Art-Decor term

**Comment by ziegm** [comment]
@pjolo please review the [PR](https://github.com/hl7ch/ch-emed/pull/257):
* move terminology to [CH Term](https://build.fhir.org/ig/hl7ch/ch-epr-term/terminology.html)
* update [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue256_term/changelog.html)

**Comment by pjolo** [comment]
The changes are good for me.
