### ISSUE TITLE
PMLC: Last document to touch treatment instance (med statement)

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#262]
Within the frame of CARA's eMedication project, we have encountered that one of the systems is basing their synchronization with the eMedication on reading PMLC documents. On this regard, some mechanism to know whether a treatment [instance] has been _touched_ (either changed, commented or any other action) would be needed or at least very nice to have: https://github.com/CARA-ch/ch-emed-epr/issues/62

We thought of adding a reference containing the last document to have touched the treatment instance to be enough for this purpose and we saw in principle two ways of doing this:

- Adding an extension (same as we have `treatmentplan` and `prescription` extensions) to contain the references to the last document/entry to have touched the treatment instance.
  - In favor: it is very explicit.
  - Against: the extension would have to be added.
- Using a meta field, for instance `meta.source` to containg the id of the last document to have touched the treatment instance.
  - In favor: already present in the IG, althought not supported by CH EMED EPR at the moment.
  - Against: not very explicit, might be easily missed by implementers.

The very idea of just using the id of the last document to have touched a treatment for this purpose is also not without cons: 

- In favor:
  - It does provide enough information for what has been requested at the moment and a reference for a document retrieval for more information if needed.
  - Minimal information to be provided makes it quite straight-forward: easier to implement.
- Against:
  - If more information would be needed/desired in the future (e.g. what kind of document did last touch the treatment instance?), then another addendum/addenda would be needed. Then again, for more information a retrieval of the original document might be a better idea.
  
In principle, at HUG we are inclined towards the `meta.source` solution but we would also like to consider any other feedback other people might want to provide on this issue.

**Comment by ziegm** [comment]
@dvribeira I am not sure, if I understand the use case correct. Could you maybe make an example (e.g. use case description) how it would work for the existing use case https://fhir.ch/ig/ch-emed/usecase-german.html?

**Comment by dvribeira** [comment]
@ziegm  Absolutely:

1. First consultation with GP:

|Doc type|Operation|Document identifier|Entries|
|------------|-------------|--------------------------|---------|
| MTP      | Export    |c9f758a1-296c-4710-84d4-e181db8c7478|MedicationStatement Triatec|
| DIS       | Export    |488bd23a-20c6-11e6-b67b-9e71128cae77|MedicationDispense Triatec|

2. Control by GP:
The GP system would fetch a PMLC and not a PML:

|Doc type|Operation|Document identifier|Entries|Entry meta.source?|
|------------|-------------|--------------------------|---------|--------------------------|
| PMLC    | Import    |17931678-20b4-11e6-b67b-9e71128cae77|MedicationStatement Triatec|488bd23a-20c6-11e6-b67b-9e71128cae77|
| PADV | Export | 8ed02d0a-2971-11e6-b67b-9e71128cae77 | Observation CANCEL | N/A |
| MTP  | Export | 17931678-20b4-11e6-b67b-9e71128cca77 | MedicationStatement Beloc Zok | N/A |
| DIS   | Export | d8143fea-4778-11e6-beb8-9e71128cae77  | MedicationDispense Beloc Zok | N/A |
| MTP | Export | 5712fffe-20c6-11e6-b67b-9e71128cae77 | MedicationStatement Norvasc | N/A |
| PRE | Export | d41d72ba-2100-11e6-b67b-9e71128cae77 | MedicationRequest Norvasc | N/A |

3. Medication card created by GP:

|Doc type|Operation|Document identifier|Entries|Entry meta.source?|
|------------|-------------|--------------------------|---------|--------------------------|
| PMLC    | Import    |6b6ed376-a7da-44cb-92d1-e75ce1ae73b0| --- | --- |
| ---------- | ----------- | -------------------| MedicationStatement Beloc Zok | d8143fea-4778-11e6-beb8-9e71128cae77 |
| ---------- | ----------- | -------------------| MedicationStatement Norvasc | d41d72ba-2100-11e6-b67b-9e71128cae77  |

---

Since the IPAG use case does not really showcase the issue under discussion in which different systems work on the same treatment plan, I am providing the following sequence:

1. The patient has a consultation at the hospital and the hospital system exports (omitting initial sync):

|Doc type|Operation|Document identifier|Entries|
|------------|-------------|--------------------------|---------|
| MTP      | Export    |c9f758a1-296c-4710-84d4-e181db8c7478|MedicationStatement Triatec|
| DIS       | Export    |488bd23a-20c6-11e6-b67b-9e71128cae77|MedicationDispense Triatec|
| MTP      | Export | 17931678-20b4-11e6-b67b-9e71128cca77 | MedicationStatement Dafalgan|

The hospital system stores, among other information, the id of the last document/intervention they have done per treatment, that is the Triatec's DIS id and the Dafalgan's MTP id.

2. The patient returns to the hospital, the hospital's system performs a sync and to that effect it fetches a PMLC:

|Doc type|Operation|Document identifier|Entries|Entry meta.source?|
|------------|-------------|--------------------------|---------|--------------------------|
| PMLC    | Import    |6b6ed376-a7da-44cb-92d1-e75ce1ae73b0| --- | --- |
| ---------- | ----------- | -------------------| MedicationStatement Triatec | 488bd23a-20c6-11e6-b67b-9e71128cae77 |
| ---------- | ----------- | -------------------| MedicationStatement Dafalgan | 17931678-20b4-11e6-b67b-9e71128cca77  |

The hospital system knows there are have been no changes performed on these treatments since the _last to touch_ ids match the ones stored by itself. No changes on the patient's treatments are performed at this time.

3. The patient goes to the GP for a control. The GP's system retrieves a PMLC to recover the current treatments for the patient but it does not have any persistence for the eMedication so no synchronization operations are performed. The GP wants to change the dosage of the Dafalgan treatment, so the system exports a PADV (CHANGE).

|Doc type|Operation|Document identifier|Entries|Entry meta.source?|
|------------|-------------|--------------------------|---------|--------------------------|
| PMLC    | Import    |6b6ed376-a7da-44cb-92d1-e75ce1ae73b0| --- | --- |
| ---------- | ----------- | -------------------| MedicationStatement Triatec | 488bd23a-20c6-11e6-b67b-9e71128cae77 |
| ---------- | ----------- | -------------------| MedicationStatement Dafalgan | 17931678-20b4-11e6-b67b-9e71128cca77  |
| PADV      | Export    |d41d72ba-2100-11e6-b67b-9e71128cae77|Observation (CHANGE) Dafalgan|N/A|

4. The patient returns to the hospital. The hospital system has to perform a sync operation for which it fetches a PMLC to get the consolidated treatment data:

|Doc type|Operation|Document identifier|Entries|Entry meta.source?|
|------------|-------------|--------------------------|---------|--------------------------|
| PMLC    | Import    |6b6ed376-a7da-44cb-92d1-e75ce1ae73b0| --- | --- |
| ---------- | ----------- | -------------------| MedicationStatement Triatec | 488bd23a-20c6-11e6-b67b-9e71128cae77 |
| ---------- | ----------- | -------------------| MedicationStatement Dafalgan | d41d72ba-2100-11e6-b67b-9e71128cae77 |

The hospital system detects that the _last to touch_ id for the dafalgan treatment does not match the stored one so it will offer the healthcare professional to import the new data (or perform it automatically and display some graphical indicator of this).

---

I hope this helps a bit to understand one of the use cases in which this information might come handy or might be needed. In our case this seems to be needed by the HUG to reliably integrate their software within our eMedication service. I have used meta.source to illustrate the use cases but as said could be an extension or any other solution.

**Comment by ziegm** [comment]
21.03.2024 Telco PJ, DV, QL, MZ, AB

Var 1:
- https://hl7.org/fhir/R4/resource.html#Meta
   - versionId & lastUpdated require
   - use the Document identifier of the last touched document
   - Issue: deletion of the document

Var 2:
- Extension on the entry level (MedicationStatement) which contains the Document identifier of the last touched document
   - Simple extension of type identifier
   - name: ch-emed-ext-last-considered-document
   - Description:

**Comment by ziegm** [comment]
@pjolo @dvribeira please review the changes:
- add [extension](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue262_lastConsidered/StructureDefinition-ch-emed-ext-last-considered-document.html) and include it in the [MedicationStatement CARD](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue262_lastConsidered/StructureDefinition-ch-emed-medicationstatement-card.html)
- [example](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue262_lastConsidered/MedicationStatement-NotRecommendedTimingCodes.html)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue262_lastConsidered/changelog.html)

**Comment by dvribeira** [comment]
@ziegm The changes are good for me, thanks! :)

**Comment by pjolo** [comment]
The changes are also good for me
