### ISSUE TITLE
Inconsistency in the data set and PDF

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-emed#267]
Hello, Patrick,

I hope you are well.

I'd like to contact you about the problem with the display of drug units in the Emedication profile.
During SIA monitoring of the test case, we noticed an inconsistency in the data provided.

As explained in Vincent's e-mail, this is what is expected in fhir.ch (see screenshot 1) 
 
![image](https://github.com/hl7ch/ch-emed/assets/87263053/6ba82998-8342-401f-bc39-516f5e0b28d5)

and the result provided by the SUT Operator (see screenshot 2).

 
![image](https://github.com/hl7ch/ch-emed/assets/87263053/b9a7aa1c-79f4-4593-9694-823c35cfff2f)

By analyzing the dataset (XML file available here), we found that the body of the XML message conforms to the expectations of (capture 1). 
However, at the end of the file, there's a ContentType tag that integrates the content of the PDF file (see screenshot below).

 
![image](https://github.com/hl7ch/ch-emed/assets/87263053/501d15a8-3bde-4fd5-821b-7fdabe68814f)

The data in this PDF file, as displayed by the editors in SIA and at Projectathon, show some deviations, particularly with regard to the display of value units, from the results expected according to fhir.ch (extract capture 1). 
In addition, this data does not align with the rest of the XML file body.

In the context of the PAT or a SIA test session, this discrepancy may cause problems during monitoring, between the expected result and the one displayed. 
Is it possible to correct this or replace the file with the correct values?

**Comment by ziegm** [comment]
01.05.2024 PJ/OE/MZ:
- 'Dosis pro Wirkstoff' => remove in UC tables
- 'Dosis pro Einheit': 50 mg vs. 50 mg / Tabl -> there is no formal definition how to represent that field in the use case table or in a representation in a medication plan => fix PDF
- 'Dosierung' => change PDF to "einnehmen" (according to IPAG Use Case)

**Comment by ziegm** [comment]
> 01.05.2024 PJ/OE/MZ:
> 
please review the changes -> ONGOING
* [changelog]()

> * Task 1: 'Dosis pro Wirkstoff' => remove in UC tables
* updated use case tables: [DE](https://build.fhir.org/ig/hl7ch/ch-emed/branches/267_inconsistencies/usecase-german.html), [FR](https://build.fhir.org/ig/hl7ch/ch-emed/branches/267_inconsistencies/usecase-french.html)

> * Task 2: 'Dosis pro Einheit': 50 mg vs. 50 mg / Tabl -> there is no formal definition how to represent that field in the use case table or in a representation in a medication plan => fix PDF


> * Task 3: 'Dosierung' => change PDF to "einnehmen" (according to IPAG Use Case)

**Comment by pjolo** [comment]
The adaptations are good
