### ISSUE TITLE
Review CHEMEDMedicationStatement and CHEMEDMedicationRequest reasonCode cardinality

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#268]
I had brought already before the topic of the cardinality of `reasonCode`, constrained by CH EMED to `0..1` and that one of the systems working on CARA's eMedication service had already pointed out that they support several coded reasons for their treatments.

After a meeting to discuss several points with a few healthcare professionals from the university hospitals of Geneva and Vaud, as well as @pjolo for eHealth Suisse, there was an unanimous belief that support for several coded reasons should be provided for treatment plans and prescriptions.

Would it be possible to review this element's cardinality and relax it back to the parents' `0..*` for both `CHEMEDMedicationStatement` and `CHEMEDMedicationRequest` profiles?

Thanks!

**Comment by pjolo** [comment]
> From my point of view that would be possible. The original reason for the restriction was I think the 0..1 coming from CDA. @pjolo @oliveregger what do you think?

I also think that this would be possible.

**Comment by oliveregger** [comment]
fine for me too

**Comment by ziegm** [comment]
@pjolo @dvribeira please review the changes:
* [MedicationStatement.reasonCode](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/StructureDefinition-ch-emed-medicationstatement.html)
* [MedicationRequest.reasonCode](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/StructureDefinition-ch-emed-medicationrequest.html)
* [MedicationDispense.extension:treatmentReason](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/StructureDefinition-ch-emed-medicationdispense.html)
* [MedicationAdministration.reasonCode](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/StructureDefinition-ch-emed-medicationadministration.html)
* [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/changelog.html)

**Comment by pjolo** [comment]
From my side the changes are good

**Comment by dvribeira** [comment]
@ziegm The changes are good for me too. Thanks a lot!
