### ISSUE TITLE
Update identifier slicing according to ch core (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#269]
Practitioner.identifier

https://github.com/hl7ch/ch-core/issues/287

**Comment by ziegm** [comment]
the discriminator can be removed, it is defined in CH Core (parent profile)

**Comment by ziegm** [comment]
@pjolo please review the changes:
- https://github.com/hl7ch/ch-emed/pull/270/files
- [CH EMED Practitioner](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/StructureDefinition-ch-emed-practitioner.html): no "visible" changes in the profile
- [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/updates_issues_269_268/changelog.html):

**Comment by pjolo** [comment]
The adaptations are good
