### ISSUE TITLE
Display values uncommented (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#271]
Composition.type for LOINC
- 2-1-Composition
- 2-2-Composition
- 2-6-Composition

according to https://github.com/hl7ch/ch-core/issues/289

**Comment by ziegm** [comment]
fixed through new version of ig publisher:

@pjolo please review the changes:
* add display values again (see [commit](https://github.com/hl7ch/ch-emed/pull/273/files))
* [qa](https://build.fhir.org/ig/hl7ch/ch-emed/branches/271_displayvalidation/qa.html) without error
* [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/271_displayvalidation/changelog.html)

**Comment by pjolo** [comment]
The changes are good
