### ISSUE TITLE
CHEMEDMedicationStatementList parentDocument

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#274]
Context:
When a PML is created, entries for medication statements and medication requests are of type `CHEMEDMedicationStatementList` or `CHEMEDMedicationRequestList` respectively. But these in turn can come from two original type of entries, either an original or a changed resource (e.g. a `CHEMEDMedicationStatementList` entry corresponds either to a `CHEMEDMedicationStatement` or a `CHEMEDMedicationStatementChanged`).

Now, `CHEMEDMedicationStatementList` has the following extensions:

- substitution
- parentDocument
- authorDocument
![image](https://github.com/hl7ch/ch-emed/assets/133101442/1669c4d0-5afd-4e1c-b2e8-65869efb2cbb)

The question here is, in the case of a changed medication statement included on a PML. Shouldn't `parentDocument` (and `authorDocument`) reference the original PADV? What to do in this case with the extension?
If we do this, then we are missing the reference to the original MTP, shouldn't we include also a treatmentPlan extension as done for `CHEMEDMedicationRequestList` ?

Apologies in advance if I am missing something.

**Comment by ziegm** [comment]
@dvribeira thanks for your feedback

I tried to visualize the case with MedicationStatement (would be the same for MedicationRequest)
![image](https://github.com/hl7ch/ch-emed/assets/32767151/e4998c78-1fae-4eb7-a875-411d29e97128)

Do you make it the same way?

So the "only" issue at the moment I see, is that we should change the parent profiles (grey arrows in the illustration):
- current:
   - `CHEMEDMedicationStatementList` -> `CHEMEDMedicationStatement`
   - `CHEMEDMedicationStatementChanged` -> `CHEMEDMedicationStatement`
- proposal:
   - `CHEMEDMedicationStatementList` -> `CHEMEDMedicationStatementChanged` -> `CHEMEDMedicationStatement`

would that solve your problem?

**Comment by dvribeira** [comment]
@ziegm thanks for having a look at the issue

Yes that would affect also medication requests as you have mentioned.

For the proposed solution:

- That would make `partOf`mandatory (`1..1` cardinality) for all `CHEMEDMedicationStatementList` but as we have seen not all of them would come from a PADV.
- what would the `parentDocument` extension point at? `CHEMEDMedicationStatementList` would always point to the MTP regardless of document source?

**Comment by ziegm** [comment]
@dvribeira Yes, you are right. Then new proposal, would that work?

Composition.section:list | current | additional
--- | --- | ---
entry:medicationStatement | `CHEMEDMedicationStatementList` </br>-> ch-emed-ext-treatmentplan | `CHEMEDMedicationStatementChangedList` </br> -> ch-emed-ext-pharmaceuticaladvice
entry:medicationRequest | `CHEMEDMedicationRequestList` </br>-> ch-emed-ext-prescription | `CHEMEDMedicationRequestChangedList` </br> -> ch-emed-ext-pharmaceuticaladvice
entry:medicationDispense | `CHEMEDMedicationDispenseList` </br>`CHEMEDMedicationAdministrationList` | -
entry:observation | `CHEMEDObservationList` | -

**Comment by dvribeira** [comment]
@ziegm yes that should address the whole issue

now I hope I'm not getting to a new world of pain when parsing...

thanks!

**Comment by dvribeira** [comment]
@ziegm Thanks for the changes. I'll be back from holidays next week and will have a look as soon as possible.

**Comment by dvribeira** [comment]
@qligier I think this will impact husky's parsing of PML documents, since there will be two types of `MedicationStatement` and two types of `MedicationRequest` potentially being provided with PML documents. I wanted to give you a heads-up, in case you would like to provide some feedback or raise some concerns (and should probably have done so earlier, my apologies). 

I will try to go through the changes a bit more in depth tomorrow, for what it affects CH EMED EPR.

**Comment by qligier** [comment]
Husky's parsing is already more limited than other types of documents, because HAPI doesn't support multiple classes for the same resource. I'm not sure how we could do better here.
Do you have changes in mind?

**Comment by dvribeira** [comment]
@qligier I was afraid so. Do you think it would be feasible and reasonable to use a single class (for either a `CHEMEDMedicationStatementList` or a `CHEMEDMedicationStatementChangedList`, same for medication requests) when _reading_ PML files or that would be too much of a workaround?

**Comment by dvribeira** [comment]
@ziegm Sorry for the delay, I had a look at the changes. The look good for me.

Regarding husky, we will have to find a way to make parsing work for this. I will work on it as soon as possible and once the PR for this issue is merged.

**Comment by ziegm** [comment]
@pjolo please also review the changes: https://github.com/hl7ch/ch-emed/issues/274#issuecomment-2178539788

**Comment by pjolo** [comment]
The changes are good

**Comment by dvribeira** [comment]
Sorry to reopen this, but I failed to notice the following in `CHEMEDDocumentMedicationList.fsh`:
```
* entry[MedicationStatementChanged].resource 1..
* entry[MedicationStatementChanged].resource only CHEMEDMedicationStatementChanged
* entry[MedicationRequestChanged].resource 1..
* entry[MedicationRequestChanged].resource only CHEMEDMedicationRequestChanged
```
should become
```
* entry[MedicationStatementChanged].resource 1..
* entry[MedicationStatementChanged].resource only CHEMEDMedicationStatementChangedList
* entry[MedicationRequestChanged].resource 1..
* entry[MedicationRequestChanged].resource only CHEMEDMedicationRequestChangedList
```

It is of no consequence (since the composition is correct will apply), but I thought this should be addressed out of coherence with the definition of the CHEMEDDocumentMedicationList for the other _list_ resources, e.g. `* entry[MedicationStatement].resource only CHEMEDMedicationStatementList`

**Comment by ziegm** [comment]
@dvribeira thanks for that! did the update
![image](https://github.com/hl7ch/ch-emed/assets/32767151/9f7fbd69-14b7-44be-946f-5f16101c6782)
