### ISSUE TITLE
Wrong link (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#275]
ch.fhir.ig.ch-emed#5.0.0-ballot /usecase-french.html

Link to "Rapport IPAG Cybermédication" does not lead to the PDF in French.
Please update it with: https://www.e-health-suisse.ch/upload/documents/Rapport_IPAG_Cybermedication.pdf

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
The change are good.
