### ISSUE TITLE
Update Figures of Documents (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#278]
ch.fhir.ig.ch-emed#5.0.0-ballot /medication-list-document.html

Replace the entry Practitioner with PractitionerRole (Practitioner isn't referred directly in the Composition anymore)

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo please review the changes:
- fig of docs
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/medication-card-document.html
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/medication-list-document.html
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/pharmaceutical-advice-document.html
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/medication-dispense-document.html
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/medication-prescription-document.html
   - https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/medication-treatment-plan-document.html
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/278_figDocs/changelog.html)

**Comment by pjolo** [comment]
The changes are good.
