### ISSUE TITLE
Issues with CHEMEDDosageMedicationRequest

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#283]
I've noticed two things in [CHEMEDDosageMedicationRequest](https://github.com/hl7ch/ch-emed/blob/master/input/fsh/profiles/CHEMEDDosageMedicationRequest.fsh) that I think are issues:

1. `doseAndRate` is required, making the free text dosage instructions invalid in prescriptions. Related to https://github.com/hl7ch/ch-emed/issues/200.

2. The constraint ch-dosage-3 makes no sense: `patientInstruction.exists() or timing.exists() or asNeeded.exists()`. AsNeeded does not belong here, it's purely optional. It should be `patientInstruction.exists() or timing.exists()`, and this should apply to CHEMEDDosage as well.

**Comment by ziegm** [comment]
24.07.2024 PJ/QL/MZ:
discussed at telco and good to merge.
