### ISSUE TITLE
CHEMEDDocumentMedicationList entry slicing is ambiguous

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-emed#285]
The slicing rules of https://github.com/hl7ch/ch-emed/blob/master/input/fsh/profiles/CHEMEDDocumentMedicationList.fsh make it so that actual validation of PML documents containing _changed_ entries will never be successful (tested with matchbox 3.5.3 with CH EMED 4.0.1, but I believe the problem still applies):

- changed resources distinguish themselves from not changed resources by having the `partOf` element/slice set as mandatory, while it is optional for original resources
- when a resource does not have a `partOf` element (in our case, any original resource), validation it is not ambiguous as it cannot be a changed resource (which requires this element) -> validation passes
- when a resource does have a `partOf`, the validator will not know against with resource profile it should be matched, since both do, and validation will fail.

```
* entry contains
    MedicationStatement 0..* and
    MedicationRequest 0..* and
    MedicationDispense 0..* and
    MedicationAdministration 0..* and
    Observation 0..* and
    MedicationStatementChanged 0..* and
    MedicationRequestChanged 0..*
* entry[MedicationStatement].resource 1..
* entry[MedicationStatement].resource only CHEMEDMedicationStatementList
* entry[MedicationRequest].resource 1..
* entry[MedicationRequest].resource only CHEMEDMedicationRequestList
* entry[MedicationDispense].resource 1..
* entry[MedicationDispense].resource only CHEMEDMedicationDispenseList 
* entry[MedicationAdministration].resource 1..
* entry[MedicationAdministration].resource only CHEMEDMedicationAdministration
* entry[Observation].resource 1..
* entry[Observation].resource only CHEMEDObservationList
* entry[MedicationStatementChanged].resource 1..
* entry[MedicationStatementChanged].resource only CHEMEDMedicationStatementChangedList
* entry[MedicationRequestChanged].resource 1..
* entry[MedicationRequestChanged].resource only CHEMEDMedicationRequestChangedList
```

The proposal would be to remove the distinction between original and changed resources at the document entry level, since they are anyway discriminated at the composition/references level and to use the CH EMED parent profiles. It should be enough to use `CHEMEDMedicationStatement` and `CHEMEDMedicationRequest` at this level instead:
```
* entry contains
    MedicationStatement 0..* and
    MedicationRequest 0..* and
    MedicationDispense 0..* and
    MedicationAdministration 0..* and
    Observation 0..*
* entry[MedicationStatement].resource 1..
* entry[MedicationStatement].resource only CHEMEDMedicationStatement
* entry[MedicationRequest].resource 1..
* entry[MedicationRequest].resource only CHEMEDMedicationRequest
* entry[MedicationDispense].resource 1..
* entry[MedicationDispense].resource only CHEMEDMedicationDispenseList 
* entry[MedicationAdministration].resource 1..
* entry[MedicationAdministration].resource only CHEMEDMedicationAdministration
* entry[Observation].resource 1..
* entry[Observation].resource only CHEMEDObservationList
```

Optionally, but not required to solve the issue, would be to also _downgrade_ the dispense and observation slices to the parent resources out of consistency. No strong opinion there on my side.

**Comment by ziegm** [comment]
> (tested with matchbox 3.5.3 with CH EMED 4.0.1, but I believe the problem still applies)

Yes, I have also encountered this problem in a similar project

**Comment by ziegm** [comment]
@dvribeira @pjolo please review the changes:
- profile [CH EMED Medication List Document](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue285_slicing/StructureDefinition-ch-emed-document-medicationlist.html)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue285_slicing/changelog.html)

**Comment by dvribeira** [comment]
The changes are good for me.

Thanks a lot!

**Comment by pjolo** [comment]
The changes are also good for me.
