### ISSUE TITLE
Typo (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#288]
ch.fhir.ig.ch-emed#5.0.0-ci-build /extensions.html

Prescritpion instead of Prescription

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo please review the [changes](https://github.com/hl7ch/ch-emed/pull/291/files)
- fixed typo in [CH EMED Extension Prescription](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue288_typo/StructureDefinition-ch-emed-ext-prescription.html)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue288_typo/changelog.html)

**Comment by pjolo** [comment]
The change is good
