### ISSUE TITLE
Add relationship to parent documents in medication list

### ISSUE THREAD

**Issue by SabrinaVivien** [hl7ch/ch-emed#289]
a medication statement in a ~~medication treatment plan document~~ medication list document is referenced by 2 identifiers (resource identifier, document identifier). Currently we only have 1 identifier and the other identifier is missing. Medication lists already profiles medication statement and medication list to add a parent document extension, that this information can be added.
Suggest to adapt example in the IG.
https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue272_medicationRequestNorvasc/relationship-between-documents.html

adding in the 2-1 Medication Statement entry parent extension: https://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-list.html
adding in the 2-1 Medication Dispense entry parent extension: https://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationdispense-list.html

edited, 20.08.24 (see comment below)

**Comment by ziegm** [comment]
> a medication statement in a medication treatment plan document ...

@SabrinaVivien don't you mean a medication statement in a medication list document?

> ... is referenced by 2 identifiers (resource identifier, document identifier). Currently we only have 1 identifier and the other identifier is missing. Medication lists already profiles medication statement and medication list to add a parent document extension, that this information can be added. Suggest to adapt example in the IG. https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue272_medicationRequestNorvasc/relationship-between-documents.html
> 
> adding in the 2-1 Medication Statement entry parent extension: https://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-list.html adding in the 2-1 Medication Dispense entry parent extension: https://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationdispense-list.html

**Comment by ziegm** [comment]
Please have a look at the changes at the telco at 04.10.2024 (PJ/OE/SK):
see comment [here](https://github.com/hl7ch/ch-emed/issues/272#issuecomment-2312772362)
