### ISSUE TITLE
Original representation: reference Binary in narrative (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#292]
New IG publisher error:

Bundle/2-7-MedicationCard-UUIDfullUrl

Bundle (l1/c2) | error | Slice 'Bundle.entry:Composition': a matching slice is required, but not found (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard\|5.0.0-ci-build). Note that other slices are allowed in addition to this required slice
-- | -- | --
Bundle​.entry[0]​.resource​/*Composition​/d543ae7b-3a94-4a2a-a120-6ce2ee3027fc*​/​.section[2]​.text​.div (l88​/c171) | error | Hyperlink scheme 'urn' in 'urn:uuid:d5c77e2e-798d-4437-8f73-4875c35065ef' at 'div/a' for 'Representation of the original view' is not a valid hyperlinkable scheme
Bundle​.entry[0]​.resource​.section[2]​.text​.div (l88​/c171) | error | Hyperlink scheme 'urn' in 'urn:uuid:d5c77e2e-798d-4437-8f73-4875c35065ef' at 'div/a' for 'Representation of the original view' is not a valid hyperlinkable scheme

**Comment by ziegm** [comment]
@pjolo: please review

Changes:
- adapt the [2-7 CARD UUID](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue292_hyperlink/Bundle-2-7-MedicationCard-UUIDfullUrl.json.html) according to the 2-7 CARD: use img tag instead of the a tag (see [comment above](https://github.com/hl7ch/ch-emed/issues/292#issuecomment-2302001926))
   - also for [2-6 PRE](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue292_hyperlink/Bundle-2-6-MedicationPrescription.json.html), because we described it in the [guidance](https://github.com/hl7ch/ch-emed/blob/master/input/pagecontent/representation.md) like that
- [QA](): suppressed the build errors (in the narrative view of the ig) and added the link to the guidance (added there the link to the zulip discussion)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue292_hyperlink/changelog.html)

**Comment by pjolo** [comment]
The changes are fine for me.
Wouldn't it make sense if this guidance of the representation is linked in the IG? 

I have found typos in the guidance:
![image](https://github.com/user-attachments/assets/d476f147-9e68-427b-9481-3e8acef1c6c5)

**Comment by ziegm** [comment]
@pjolo as discussed before:
- updated section [Implication of MustSupport to the Original Representation](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue292_hyperlink/index.html#implication-of-mustsupport-to-the-original-representation)
- added there link to [handling narrative](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue292_hyperlink/original-representation.html)

**Comment by pjolo** [comment]
The changes are good.
