### ISSUE TITLE
Typo (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#295]
CH EMED (R4)

SNOWMED CT immer wieder derselbe Fehler wegen der falschen Aussprache, hat mit Schnee nichts zu tun: SNOMED CT

Marcel Hanselmann

**Comment by qligier** [comment]
Related bug in FHIR Core: https://github.com/hapifhir/org.hl7.fhir.core/pull/1623/files

**Comment by ziegm** [comment]
> Related bug in FHIR Core: https://github.com/hapifhir/org.hl7.fhir.core/pull/1623/files

@lpg-tech where did you see those typos?

**Comment by ziegm** [comment]
https://fhir.ch/ig/ch-emed/5.0.0-ballot/MedicationStatement-2-7-MedStatBeloczok.html
There is an issue in the generated narrative (tooling issue).

In the meantime it is fixed:
https://build.fhir.org/ig/hl7ch/ch-emed/MedicationStatement-2-7-MedStatBeloczok.html

Added the issue in the changelog: https://build.fhir.org/ig/hl7ch/ch-emed/changelog.html

@pjolo please review

**Comment by pjolo** [comment]
Everything's fine for me
