### ISSUE TITLE
2-5 Medication Treatment Plan document - XML Representation (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#297]
ch.fhir.ig.ch-emed#5.0.0-ci-build /Bundle-2-5-MedicationTreatmentPlan.xml.html

Example Instances: Since CH Core Medication has an optional GTIN code, it could be used in the Examples to identify the Medication. 

Marcel Hanselmann

**Comment by qligier** [comment]
[/Bundle-1-1-MedicationTreatmentPlan.html](https://build.fhir.org/ig/hl7ch/ch-emed/Bundle-1-1-MedicationTreatmentPlan.html) and [/Bundle-2-3-MedicationTreatmentPlan.html](https://build.fhir.org/ig/hl7ch/ch-emed/Bundle-2-3-MedicationTreatmentPlan.html) are examples of MTPs with a GTIN.
2-5 is useful as an example without a GTIN, specifically.

**Comment by ziegm** [comment]
The mentioned example https://fhir.ch/ig/ch-emed/Bundle-2-5-MedicationTreatmentPlan.xml.html does have a GTIN (urn:oid:2.51.1.1):

``` xml
          <Medication>
            <id value="Norvasc"/>
            <meta>
              <profile
                       value="http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medication"/>
            </meta>
            <code>
              <coding>
                <system value="urn:oid:2.51.1.1"/>
                <code value="7680500440334"/>
                <display value="NORVASC Tabl 10 mg"/>
              </coding>
              <text value="NORVASC Tabl 10 mg"/>
            </code>

```

![image](https://github.com/user-attachments/assets/53ea4a46-2542-4f60-a48b-0ad9544f1df5)


What we could do, to improve the readablity of the IG, we could add a more detailed description to the different examples here:
https://fhir.ch/ig/ch-emed/5.0.0-ballot/artifacts.html#4
Then it is more obvious where to find what.

@lpg-tech @pjolo 
would you agree with that proposal?

**Comment by pjolo** [comment]
@lpg-tech I am not sure if I have understood the issue correctly. Do you miss GTIN in the example or is it a statement that GTIN can be used? 

@ziegm I agree with that proposal

**Comment by ganimedes** [comment]
I agree with the proposal, and the GTIN in the example would be helpful.

**Comment by ziegm** [comment]
> I agree with the proposal, and the GTIN in the example would be helpful.

@lpg-tech The GTIN is already included. Or do you mean something different?

**Comment by ziegm** [comment]
@pjolo @lpg-tech please review the changes:
- [updated descriptions of the examples](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/artifacts.html#4)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

**Comment by pjolo** [comment]
> @pjolo @lpg-tech please review the changes:
> 
> * [updated descriptions of the examples](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/artifacts.html#4)
> * [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html)

@ziegm: From my side, the changes are good

**Comment by lpg-tech** [comment]
@ziegm @pjolo 
Changes are perfect.
I still dont understand why the medication Reference is self-reflexive, and doesn't link the Medication 'Norvasc':
![2-5 Medication Statement with Medication Norvasc-0-1](https://github.com/user-attachments/assets/6571325b-919b-4192-9974-3bc574c537a7)

**Comment by ziegm** [comment]
because the medication is contained in the medicationstatement:

![image](https://github.com/user-attachments/assets/f497ffab-329c-4542-9f05-44c08127e46d)
