### ISSUE TITLE
Pharmaceutical Advice document (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#298]
ch.fhir.ig.ch-emed#5.0.0-ci-build /pharmaceutical-advice-document.html

See: Modifying an existing medication, CHANGE
The common and important Use Case is the substitution of an original drug with a generica, e.g. NORVASC with AMLODIPIN Spirig. So a corresponding example would be helpful.

Marcel Hanselmann

**Comment by ziegm** [comment]
We already integrated that use case:
"Prescription can be dispensed after indicated change. The Observation ([example](https://fhir.ch/ig/ch-emed/Observation-PharmaceuticalAdvice-ChangeMedicament.html)) refers the original Medication Prescription document and a new MedicationRequest ([example](https://fhir.ch/ig/ch-emed/MedicationRequest-MedReq-ChangeMedication.html)) with the changed information."
Observation.note: Generika: Amlodipin anstatt Norvasc

In that case, my proposal would be, to update the descriptions, that it is more obvious, what the examples are all about.

@pjolo @lpg-tech
do you agree with that proposal?

**Comment by ganimedes** [comment]
@pjolo @ziegm 
 I agree

**Comment by ziegm** [comment]
@pjolo @ganimedes please review the updates:
* Update description of section and examples for CHANGE (dosage change):
   * [section](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/pharmaceutical-advice-document.html#modifying-an-existing-medication)
   * [Observation](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/Observation-Obs-ChangeDosage.html)
   * [MedicationStatement](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/MedicationStatement-MedStatTriatec-ChangeDosage.html)
* Update description of section and examples for CHANGE (generic medication):
   * [section](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/pharmaceutical-advice-document.html#modifying-an-existing-medication)
   * [Observation](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/Observation-PharmaceuticalAdvice-ChangeMedicament.html)
   * [MedicationRequest](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/MedicationRequest-MedReq-ChangeMedication.html)
* [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue298_padvChange/changelog.html)

**Comment by ganimedes** [comment]
@pjolo @ziegm : perfect

**Comment by pjolo** [comment]
The changes are good.
