### ISSUE TITLE
CH EMED Medication Card Composition - Define Link from narrative to binary (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#300]
ch.fhir.ig.ch-emed#5.0.0-ballot /StructureDefinition-ch-emed-composition-medicationcard.html

The link from narrative text to resources has been precised, that a link in the narrative should point to an entry.id.

See zulip discussion here: https://chat.fhir.org/#narrow/stream/207835-IPS/topic/Referencing.20from.20IPS.20narrative.20to.20data

We should make the entry.id mandatory on the original presentation where the binary resource is. Need to adapt the examples narrative where we require the originalRepresentation (MedicationCard, Prescription).

Oliver Egger, ahdis

**Comment by dvribeira** [comment]
Maybe I am missing some context, but I fail to see why entry.id (for the original representation) should be **mandatory**. I understand it is needed for linking it within the composition narrative. But is this linking within the Composition narrative specified as mandatory anywhere? Or is the idea here that original representations here should contain an entry.id so they could be used as such when producing an IPS?

Apologies if I am making any silly question, I just want to be sure I understand the full implications of this change and the reasoning behind it.

**Comment by ziegm** [comment]
Preparation for meeting 03.10. PJ/OE/MZ:

Changes CH EMED:
- updated the examples [2-6 PRE](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/Bundle-2-6-MedicationPrescription.json.html), [2-7 CARD](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/Bundle-2-7-MedicationCard.json.html)
- remove guidance with open points about original representation
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/changelog.html)

Proposal how to continue:
- Update min card for Compositon.section:originalRepresentation.entry.id to 1 in the base profile [CH Core Composition EPR](https://fhir.ch/ig/ch-core/5.0.0-ballot/StructureDefinition-ch-core-composition-epr.html)
- Add Guidance for it in CH Core (link it in CH EMED ([here](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/index.html#implication-of-mustsupport-to-the-original-representation)))
- Raise issues in the other Swiss IGs where examples do use the original representation

**Comment by ziegm** [comment]
- Update example: change id from section.id to bundle.entry.id
- not required in profile

**Comment by ziegm** [comment]
> Maybe I am missing some context, but I fail to see why entry.id (for the original representation) should be **mandatory**. I understand it is needed for linking it within the composition narrative. But is this linking within the Composition narrative specified as mandatory anywhere? Or is the idea here that original representations here should contain an entry.id so they could be used as such when producing an IPS?
> 
> Apologies if I am making any silly question, I just want to be sure I understand the full implications of this change and the reasoning behind it.

@dvribeira you are right. we moved the id from Composition.section.id to Bundle.entry.id. And we do a guidance section in CH Core, link it in CH EMED and show there an example. We do not restrict anything in the profiles.
Do you agree with these steps?

**Comment by dvribeira** [comment]
@ziegm All good. I just wanted to be sure I had a good understanding of the issue. Thanks!

**Comment by ziegm** [comment]
@pjolo please review the changes:
- updated examples 
   - [2-6 PRE](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/Bundle-2-6-MedicationPrescription.json.html)
   - [2-7 CARD](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/Bundle-2-7-MedicationCard.json.html)
   - [2-7 CARD UUID](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/Bundle-2-7-MedicationCard-UUIDfullUrl.json.html) 
- update section [Implication of MustSupport to the Original Representation](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/index.html#implication-of-mustsupport-to-the-original-representation) 
   - remove link to guidance with open points about original representation
   - add new link to guidance in ch core (will work when ch core is published) -> [ci build ch core](https://build.fhir.org/ig/hl7ch/ch-core/branches/issue30_originalRepresentation/guidance.html#readable-representation-of-epr-documents)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue300_linkFromNarrative/changelog.html)

**Comment by pjolo** [comment]
The adjustments are good
