### ISSUE TITLE
Link sections for a better navigations (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#301]
ch.fhir.ig.ch-emed#5.0.0-ballot /pharmaceutical-advice-document.html

https://fhir.ch/ig/ch-emed/pharmaceutical-advice-document.html

Link from the mentioned use cases at the top of the page to the according sections on the lower part of this page:

- Modifying an existing medication
- Adding a comment on an existing medication

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo please review the updates:
* Add links for mentioned sections _Modifying an existing medication_ & _Adding a comment on an existing medication_ in the upper part of the page [Pharmaceutical Advice document](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue301_addLinks/pharmaceutical-advice-document.html)
* [Changelog](https://build.fhir.org/ig/hl7ch/ch-emed/branches/issue301_addLinks/changelog.html)

**Comment by pjolo** [comment]
Good
