### ISSUE TITLE
InRes missing (Daniel Ratschiller, Cistec AG & Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#72]
ch.fhir.ig.ch-emed#1.0.0 /

Missing or unclear possibility to document the status "in reserve" for a medication, as it is possible in the CHMED16A format with the field "InRes". Perhaps the field "asNeeded" should be used for this purpose? http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-dosage-structured-split-definitions.html#Dosage.asNeeded[x].

Cistec AG

**Comment by ziegm** [comment]
- Nicht im Minimal Daten Set IPAG, IPAG hat gibt es das Element "Grundmedikation oder Reservemedikation" empfohlen/wichtig.
- CHMED16A: InRes = Reservemedikation?
- TBD: Representation CDA?

Hypothese: Im CHMED20AF abbilden, nicht definieren im CH EMED.

**Comment by drats-cis** [comment]
Das Ticket ist tatsächlich von Cistec/mir. Wir haben 2 konkrete Spitäler mit dem Bedarf aus dem praktischen Alltag, Medikation in Reserve auch im Rezept adressieren zu können. Dazu gehört oft eine klinische Bedinung (z.B. bei Schmerzen, bei Bluthochdruck) und manchmals sogar eine Priorität (Abstufung, erst das weniger starke, dann das stärkere). Diese Informationen auf einer Dosierungskarte @Patient sind demnach offenbar doch auch gefragt auf dem Rezept @Apotheker.
Dass es im CHMED21AF berücksichtigt werden wir finde ich super. Ich würde es aber auch in CH-EMED sinnvoll finden und meinte anhand der Beschreibung unter "Dosage.asNeeded", siehe Link im Issue, bereits das geeingete Feld dafür gefunden zu haben: "A coded concept identifying the precondition that should be met or evaluated prior to consuming or administering a medication dose. For example "pain", "30 minutes prior to sexual intercourse", "on flare-up" etc.

**Comment by ziegm** [comment]
TBD @ Telco:
- Wie wird für ein neues Release vorgegangen? 
- Wie können mehr strukturierte Daten abgebildet werden?
- Weitere Erarbeitung mit IPAG -> Minimal Data Set?
- Kann dieser Antrag als Feature Request für das nächste Release übernommen werden?

**Comment by ziegm** [comment]
Telco für das Element InRes:
Entscheid, das als Feature Request für ein nächstes Release zu übernehmen.

**Comment by ziegm** [comment]
@drats-cis : siehe Entscheid vom 02.12.2021

**Comment by qligier** [comment]
It has been added to CDA-CH-EMED; see [the template](https://art-decor.org/art-decor/decor-templates--ch-pharm-?id=2.16.756.5.30.1.1.10.10&effectiveDate=2022-02-24T09:27:22) and [the value set](https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.1.11.85&effectiveDate=2022-02-25T13:26:58).

**Comment by oliveregger** [comment]
Patrick Jolo: Gerne möchte ich euch die Rückmeldungen aus der IPAG Arbeitsgruppe mitteilen.

Betreffend Reservemedikation:
Die IPAG AG hat zu diesem Thema zurückgemeldet, dass sie dieses Thema lange diskutiert haben und die Reservemedikationen auf Grund der Komplexität in das Kommentarfeld dokumentieren. Sie haben dies auch in der Umsetzungshilfe auf [Seite 21 (Punkt 5)](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/D/Umsetzungshilfe_Medikationsplan_DE.pdf#page=22) und [Seite 24 «Reserve-Medikamente»](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/D/Umsetzungshilfe_Medikationsplan_DE.pdf#page=25) empfohlen.

**Comment by ziegm** [comment]
Neuster Stand:
* Abbildung wird im produktiven Umfeld benötigt, siehe 
   * https://github.com/hl7ch/ch-emed/issues/117
   * https://qligier.github.io/cara-emed-ig/cdachemed/mtp/#in-reserve

**Comment by walterwellauer** [comment]
Does this reaffirmation that this is really needed mean that it will be included in STU3 or do we have to wait for a STU4 to be included?

**Comment by ziegm** [comment]
@pjolo 
Bitte erneute Evaluation, ob dieses Element abgebildet werden kann in den Dosage-Profilen:
* [Strukturierte Dosierung](http://build.fhir.org/ig/hl7ch/ch-emed/branches/projectathon2022/StructureDefinition-ch-emed-dosage-structured.html)
* [Unstrukturierte Dosierung](http://build.fhir.org/ig/hl7ch/ch-emed/branches/projectathon2022/StructureDefinition-ch-emed-dosage-nonstructured.html)

**Comment by ziegm** [comment]
Telco with Patrick, 20.10.2022:
* Strukturiertes Element aufnehmen. Medikamente in Reserve gehören in eine Übersicht der aktuellen Medikation.

**Comment by ziegm** [comment]
Close issue, will be merged to master with merging stu3ballotresolution branch
