### ISSUE TITLE
Dosage for Prescription too strict? (Michaela Ziegler, ahdis)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#90]
[Dosage structured normal](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-dosage-structured-normal-medicationrequest.html) and [Dosage structured split](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-dosage-structured-split-medicationrequest.html) are probably too strict (timing/doseAndRate).

Reason in mapping to [IPAG report](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2017/D/170607_Bericht_eMedikation_IPAG.pdf):
* Anwendungsschema: **o** obligatorisch (Dosage.timing.repeat.when, Dosage.doseAndRate.dose)
* Anwendungsdauer: **oa** obligatorisch wenn anwendbar (Dosage.timing.repeat.boundsPeriod)

**Comment by pjolo** [comment]
@ziegm: I do not think this is too strict. The application scheme and duration of application should be present on a prescription. This is also required as information in the drug ordinance.
https://www.fedlex.admin.ch/eli/cc/2018/588/de#art_51

What is the reason why this is too strict?

**Comment by ziegm** [comment]
@pjolo 
The question arises whether all information is always available.
- In [these examples (p. 6)](https://www.kantonsapotheker.ch/fileadmin/docs/public/kav/2_Leitlinien___Positionspapiere/H_010_Positionspapier_a__rztliche_Verschreibungen_Version_2.pdf), the start and end dates are not explicitly specified.
- In the eMediplan (Rx), these two dates are also not required. 
- According to IPAG, it is also only "oa (obligatorisch wenn anwendbar)".

Could we therefore reduce at least Dosage.timing.repeat.boundsPeriod to 0..1?
