### ISSUE TITLE
Extension Substitution also in Medication Card document? (Michaela Ziegler, ahdis)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#91]
[MedicationStatement Treatment Plan](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-treatmentplan.html) with [Extension for Substitution](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-substitution.html)
[MedicationStatement Card](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-card.html) **without** [Extension for Substitution](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-substitution.html)

Possibly to consider whether to allow it for the card as well. CHMED does this, for example (see [here](http://build.fhir.org/ig/ahdis/chmed/branches/master/StructureDefinition-chmed-card-medicationstatement.html)).

_Note -> it is already represented in other documents: [MedicationRequest.substitution](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationrequest.html), [MedicationDispense.substitution](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationdispense.html)_

**Comment by oliveregger** [comment]
Patrick JoloL Betreffend Substitutionen:

Die IPAG ist der Meinung, dass das Medication Card document der falsche Ort ist für die Substitutionen. Sie sehen das Problem, dass es zu viele Varianten gibt für die korrekte Abbildung und es zu Verwirrungen kommen kann, wenn von Kombipräparate auf Monopräparate gewechselt wird. Sie sind auch der Meinung, dass das Medication Card document im Moment so belassen und damit erstmal Erfahrungen gesammelt werden soll.

**Comment by ziegm** [comment]
I am submitting this issue for the current ballot. From my point of view, the mapping of substitution should also be possible in the Medication Card document to ensure a correct mapping of the patient's medication. Especially because it is already possible in the other documents.

IPAG: _"Sie sehen das Problem, dass es zu viele Varianten gibt für die korrekte Abbildung und es zu Verwirrungen kommen kann, wenn von Kombipräparate auf Monopräparate gewechselt wird."_
To address the IPAG concern, my suggestion would be to describe this topic in a separate "Guidance" tab with use cases and examples.

**Comment by ziegm** [comment]
@pjolo 
Bitte erneute Evaluation.

**Comment by qligier** [comment]
I would agree with IPAG, the Medication Card should not contain a substitution indication because it's not needed there.

- If you're dispensing on a Medication Card, you're doing it wrong (dispensing is done on MTP and/or PRE documents, which contain it);
- if you're not dispensing, then why would you need this information?

**Comment by ziegm** [comment]
> I would agree with IPAG, the Medication Card should not contain a substitution indication because it's not needed there.
> 
> * If you're dispensing on a Medication Card, you're doing it wrong (dispensing is done on MTP and/or PRE documents, which contain it);
> * if you're not dispensing, then why would you need this information?

HCI (Documedis) has the use case of being able to show whether or not the medication has been substituted in the Medication Card, which is an overview of the patient's current medication. This information is otherwise not visible on the card for the patient/pharmacist etc., but can be relevant.

**Comment by ziegm** [comment]
01.11.2022: asked for feedback on this at HCI

**Comment by ziegm** [comment]
> HCI (Documedis) has the use case of being able to show whether or not the medication has been substituted in the Medication Card, which is an overview of the patient's current medication. This information is otherwise not visible on the card for the patient/pharmacist etc., but can be relevant.

I must correct myself here after consulting with HCI. It can be indicated whether the medication can theoretically be substituted for this patient, i.e. whether it is allowed. (Has nothing to do with dispensing).

That could be done with adding this [Extension](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-substitution.html) to the MedicationStatement (Card). The code for it comes from the [VS ActSubstanceAdminSubstitutionCode](http://terminology.hl7.org/3.1.0/ValueSet-v3-ActSubstanceAdminSubstitutionCode.html), e.g.:
<html>
<body>


E | equivalent | **Description:** Substitution occurred or is permitted with another bioequivalent and therapeutically equivalent product.
-- | -- | --



</body>
</html>
This expresses that a substitution would be permitted.

**Comment by ziegm** [comment]
Related issue: https://github.com/hl7ch/ch-emed/issues/156 (point 3)

**Comment by pjolo** [comment]
@ziegm 
If it is only to indicate whether a medicine can be substituted, I agree with the extension being added to the MedicationStatement (Card).

**Comment by pjolo** [comment]
Ok issue can be closed
