### ISSUE TITLE
Add code to ValueSet UnitCode

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#93]
HCI is currently cleaning up their ValueSets to be congruent with those of CH EMED. To ensure this is complete in both directions, the request is made to add the following codes to the [CH EMED ValueSet UnitCode](http://fhir.ch/ig/ch-emed/ValueSet-UnitCode.html):
* **a** year (UCUM)

**Comment by pjolo** [comment]
The code was added to Art Decor
![image](https://user-images.githubusercontent.com/87263053/172650694-a63b7528-3eb0-4fde-aa4f-fef83056939b.png)
