### ISSUE TITLE
Add code to ValueSet EDQM - RouteOfAdministration

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#94]
HCI is currently cleaning up their ValueSets to be congruent with those of CH EMED. To ensure this is complete in both directions, the request is made to add the following codes to the [CH EMED ValueSet EDQM - RouteOfAdministration](http://fhir.ch/ig/ch-emed/ValueSet-edqm-routeofadministration.html):
* **20087000** extrapleurale Anwendung (EDQM)

**Comment by pjolo** [comment]
The code was added to Art Decor
![image](https://user-images.githubusercontent.com/87263053/172650385-e6ff9ac1-ea14-4325-a6f2-a72c218fc9d0.png)
